/**
 * Regenerates supabase/full_schema.sql as the exact concatenation of every migration, in
 * filename order, with a banner per file. The hand-maintained version drifted: it was missing
 * two whole migrations, so a database built from it rejected every profile write.
 *
 *   npm run build:schema          # rewrite supabase/full_schema.sql
 *   npm run check:schema          # exit 1 if the committed file differs from the migrations
 *
 * The stronger check is scripts/db/local/dump-diff.sh, which applies both to empty databases
 * and diffs the pg_dump output; concatenation makes them identical by construction, so that
 * only ever catches a hand edit.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const ROOT = path.resolve(__dirname, "../..");
const MIGRATIONS = path.join(ROOT, "supabase/migrations");
const OUT = path.join(ROOT, "supabase/full_schema.sql");

const files = readdirSync(MIGRATIONS).filter((f) => f.endsWith(".sql")).sort();
const parts = [
  "-- GENERATED by scripts/db/build-full-schema.ts from supabase/migrations/*.sql.",
  "-- Do not edit by hand: add a migration and run `npm run build:schema`.",
  `-- ${files.length} migrations.`,
  "",
];
for (const file of files) {
  const body = readFileSync(path.join(MIGRATIONS, file), "utf8").replace(/\s+$/, "");
  parts.push(`-- >>> migrations/${file}`, body, "");
}
const generated = parts.join("\n") + "\n";

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(OUT, "utf8");
  } catch {
    /* missing counts as drift */
  }
  if (current !== generated) {
    console.error("supabase/full_schema.sql is out of date — run `npm run build:schema`.");
    process.exit(1);
  }
  console.log(`supabase/full_schema.sql matches ${files.length} migrations.`);
} else {
  writeFileSync(OUT, generated);
  console.log(`wrote supabase/full_schema.sql from ${files.length} migrations.`);
}
