import type { BursaryCriteria } from "@/lib/matching/match";
import type { InterestId } from "@/lib/tags/interests";
import { CEGEP_DEC_PROGRAMS } from "@/lib/data/cegep-catalog";
import { ALL_IMPORTANT_DATES } from "@/lib/data/important-dates";

export type Cegep = { id: string; name: string; region: string };

export const CEGEPS: Cegep[] = [
  { id: "sainte-foy", name: "Cégep de Sainte-Foy", region: "Québec" },
  { id: "garneau", name: "Cégep Garneau", region: "Québec" },
  { id: "limoilou", name: "Cégep Limoilou (campus Limoilou)", region: "Québec" },
  { id: "limoilou-charlesbourg", name: "Cégep Limoilou (campus Charlesbourg)", region: "Québec" },
  { id: "champlain-slc", name: "Champlain College St. Lawrence", region: "Québec" },
  { id: "merici", name: "Collège Mérici", region: "Québec" },
  { id: "notre-dame-de-foy", name: "Campus Notre-Dame-de-Foy", region: "Québec" },
  { id: "osullivan-quebec", name: "Collège O'Sullivan de Québec", region: "Québec" },
  { id: "charlevoix", name: "Centre d'études collégiales en Charlevoix", region: "Capitale-Nationale" },
  { id: "bart", name: "Collège Bart", region: "Québec" },
  { id: "conservatoire-quebec", name: "Conservatoire de musique de Québec", region: "Québec" },
  { id: "maisonneuve", name: "Cégep de Maisonneuve", region: "Montréal" },
  { id: "vieux-montreal", name: "Cégep du Vieux Montréal", region: "Montréal" },
  { id: "ahuntsic", name: "Collège Ahuntsic", region: "Montréal" },
  { id: "bois-de-boulogne", name: "Collège de Bois-de-Boulogne", region: "Montréal" },
  { id: "dawson", name: "Dawson College", region: "Montréal" },
  { id: "vanier", name: "Vanier College", region: "Montréal" },
  { id: "marianopolis", name: "Marianopolis College", region: "Montréal" },
  { id: "saint-laurent", name: "Cégep de Saint-Laurent", region: "Montréal" },
  { id: "andre-laurendeau", name: "Cégep André-Laurendeau", region: "Montréal" },
  { id: "rosemont", name: "Collège de Rosemont", region: "Montréal" },
  { id: "marie-victorin", name: "Cégep Marie-Victorin", region: "Montréal" },
  { id: "montmorency", name: "Collège Montmorency", region: "Laval" },
  { id: "edouard-montpetit", name: "Cégep Édouard-Montpetit", region: "Montérégie" },
  { id: "champlain-saint-lambert", name: "Champlain College Saint-Lambert", region: "Montérégie" },
  { id: "saint-jean-sur-richelieu", name: "Cégep de Saint-Jean-sur-Richelieu", region: "Montérégie" },
  { id: "saint-hyacinthe", name: "Cégep de Saint-Hyacinthe", region: "Montérégie" },
  { id: "vallefield", name: "Cégep de Valleyfield", region: "Montérégie" },
  { id: "lionel-groulx", name: "Collège Lionel-Groulx", region: "Laurentides" },
  { id: "saint-jerome", name: "Cégep de Saint-Jérôme", region: "Laurentides" },
  { id: "lanaudiere-joliette", name: "Cégep régional de Lanaudière à Joliette", region: "Lanaudière" },
  { id: "lanaudiere-terrebonne", name: "Cégep régional de Lanaudière à Terrebonne", region: "Lanaudière" },
  { id: "lanaudiere-l-assomption", name: "Cégep régional de Lanaudière à L'Assomption", region: "Lanaudière" },
  { id: "sherbrooke", name: "Cégep de Sherbrooke", region: "Estrie" },
  { id: "champlain-lennoxville", name: "Champlain College Lennoxville", region: "Estrie" },
  { id: "granby", name: "Cégep de Granby", region: "Estrie" },
  { id: "trois-rivieres", name: "Cégep de Trois-Rivières", region: "Mauricie" },
  { id: "shawinigan", name: "Cégep de Shawinigan", region: "Mauricie" },
  { id: "drummondville", name: "Cégep de Drummondville", region: "Centre-du-Québec" },
  { id: "victoriaville", name: "Cégep de Victoriaville", region: "Centre-du-Québec" },
  { id: "outaouais", name: "Cégep de l'Outaouais", region: "Outaouais" },
  { id: "heritage", name: "Heritage College", region: "Outaouais" },
  { id: "chicoutimi", name: "Cégep de Chicoutimi", region: "Saguenay–Lac-Saint-Jean" },
  { id: "jonquiere", name: "Cégep de Jonquière", region: "Saguenay–Lac-Saint-Jean" },
  { id: "alma", name: "Collège d'Alma", region: "Saguenay–Lac-Saint-Jean" },
  { id: "st-felicien", name: "Cégep de Saint-Félicien", region: "Saguenay–Lac-Saint-Jean" },
  { id: "rimouski", name: "Cégep de Rimouski", region: "Bas-Saint-Laurent" },
  { id: "riviere-du-loup", name: "Cégep de Rivière-du-Loup", region: "Bas-Saint-Laurent" },
  { id: "matane", name: "Cégep de Matane", region: "Bas-Saint-Laurent" },
  { id: "la-pocatiere", name: "Cégep de La Pocatière", region: "Bas-Saint-Laurent" },
  { id: "gaspesie", name: "Cégep de la Gaspésie et des Îles", region: "Gaspésie–Îles-de-la-Madeleine" },
  { id: "abitibi", name: "Cégep de l'Abitibi-Témiscamingue", region: "Abitibi-Témiscamingue" },
  { id: "sept-iles", name: "Cégep de Sept-Îles", region: "Côte-Nord" },
  { id: "baie-comeau", name: "Cégep de Baie-Comeau", region: "Côte-Nord" },
  { id: "beauce-appalaches", name: "Cégep Beauce-Appalaches", region: "Chaudière-Appalaches" },
  { id: "levis", name: "Cégep de Lévis", region: "Chaudière-Appalaches" },
  { id: "thetford", name: "Cégep de Thetford", region: "Chaudière-Appalaches" }
];

export type CegepProgram = { id: string; name: string; type: "pre_university" | "technical" };

export const CEGEP_PROGRAMS: CegepProgram[] = CEGEP_DEC_PROGRAMS.map((p) => ({
  id: p.code,
  name: p.nameFr,
  type: p.type,
}));

export type Session = { id: number; labelFr: string; labelEn: string };

export const SESSIONS: Session[] = [
  { id: 1, labelFr: "1ère session (Automne 2026)", labelEn: "1st Semester (Fall 2026)" },
  { id: 2, labelFr: "2e session (Hiver 2027)", labelEn: "2nd Semester (Winter 2027)" },
  { id: 3, labelFr: "3e session (Automne 2027)", labelEn: "3rd Semester (Fall 2027)" },
  { id: 4, labelFr: "4e session (Hiver 2028)", labelEn: "4th Semester (Winter 2028)" },
  { id: 5, labelFr: "5e session (Automne 2028)", labelEn: "5th Semester (Fall 2028)" },
  { id: 6, labelFr: "6e session (Hiver 2029)", labelEn: "6th Semester (Winter 2029)" },
];

export type PrerequisiteStatus = "met" | "missing" | "in_progress";

export type CutoffFigureType =
  | "last_admitted"
  | "minimum_required"
  | "maximum"
  | "average"
  | "range_low"
  | "range_high";

export type CutoffSourceTier = "university_official" | "cegep_compiled";

export type CutoffEntry = {
  year: number;
  cutoff: number;
  figureType: CutoffFigureType;
  sourceTier: CutoffSourceTier;
};

export type UniversityProgram = {
  id: string;
  name: string;
  institution: string;
  description: string;
  interestIds: InterestId[];
  cohortLabel: string;
  courseFloor?: { course: string; minGrade: number; note: string };
  placementRate?: { value: number; note: string };
  professionalOrders?: { codes: string[]; note: string };
  sourceUrl: string;
  lastVerifiedAt: string;
  cutoffHistory: CutoffEntry[];
  prerequisites: { name: string; status: PrerequisiteStatus }[];
};

export const UNIVERSITY_PROGRAMS: UniversityProgram[] = [
  // --- SANTÉ & MÉDECINE ---
  {
    id: "ulaval-medecine",
    name: "Doctorat de 1er cycle en médecine (MD)",
    institution: "Université Laval",
    description: "Formation médicale complète avec externat et stages cliniques en milieu hospitalier universitaire.",
    interestIds: ["health", "science"],
    cohortLabel: "Cohorte automne 2026",
    placementRate: { value: 100, note: "Accès direct à la résidence médicale (CaRMS)." },
    professionalOrders: { codes: ["CMQ"], note: "Collège des médecins du Québec." },
    sourceUrl: "https://www.ulaval.ca/etudes/programmes/doctorat-de-1er-cycle-en-medecine",
    lastVerifiedAt: "2026-08-24",
    cutoffHistory: [
      { year: 2024, cutoff: 33.500, figureType: "last_admitted", sourceTier: "university_official" },
      { year: 2024, cutoff: 35.800, figureType: "average", sourceTier: "university_official" },
      { year: 2024, cutoff: 38.900, figureType: "maximum", sourceTier: "university_official" },
    ],
    prerequisites: [
      { name: "Calcul différentiel (201-NYA)", status: "met" },
      { name: "Calcul intégral (201-NYB)", status: "met" },
      { name: "Chimie générale (202-NYA)", status: "met" },
      { name: "Chimie des solutions (202-NYB)", status: "met" },
      { name: "Physique : Mécanique (203-NYA)", status: "met" },
      { name: "Physique : Électricité (203-NYB)", status: "met" },
      { name: "Physique : Ondes (203-NYC)", status: "met" },
      { name: "Biologie générale (101-NYA)", status: "met" },
      { name: "Biologie humaine (101-HTK ou équivalent)", status: "in_progress" },
    ],
  },
  {
    id: "udem-medecine",
    name: "Doctorat de 1er cycle en médecine (MD)",
    institution: "Université de Montréal",
    description: "Programme de doctorat en médecine intégrant formation scientifique rigoureuse, simulation clinique et apprentissage par problèmes.",
    interestIds: ["health", "science"],
    cohortLabel: "Cohorte automne 2026",
    placementRate: { value: 100, note: "Poursuite en résidence médicale." },
    professionalOrders: { codes: ["CMQ"], note: "Collège des médecins du Québec." },
    sourceUrl: "https://admission.umontreal.ca/programmes/doctorat-de-1er-cycle-en-medecine/",
    lastVerifiedAt: "2026-08-24",
    cutoffHistory: [
      { year: 2024, cutoff: 34.200, figureType: "last_admitted", sourceTier: "university_official" },
      { year: 2024, cutoff: 36.100, figureType: "average", sourceTier: "university_official" },
      { year: 2024, cutoff: 39.400, figureType: "maximum", sourceTier: "university_official" },
    ],
    prerequisites: [
      { name: "Calcul différentiel (201-NYA)", status: "met" },
      { name: "Calcul intégral (201-NYB)", status: "met" },
      { name: "Chimie générale (202-NYA)", status: "met" },
      { name: "Chimie des solutions (202-NYB)", status: "met" },
      { name: "Physique mécanique (203-NYA)", status: "met" },
      { name: "Biologie 1 (101-NYA)", status: "met" },
      { name: "Biologie 2 (101-HTK)", status: "met" },
    ],
  },
  {
    id: "mcgill-medecine",
    name: "Doctor of Medicine and Master of Surgery (MDCM)",
    institution: "McGill University",
    description: "Four-year undergraduate medical curriculum integrating patient-centred clinical immersion and cutting-edge biomedical research.",
    interestIds: ["health", "science"],
    cohortLabel: "Cohorte automne 2026",
    placementRate: { value: 100, note: "Direct CaRMS postgraduate residency placement." },
    professionalOrders: { codes: ["CMQ"], note: "Collège des médecins du Québec." },
    sourceUrl: "https://www.mcgill.ca/medadmissions/programs/mdcm",
    lastVerifiedAt: "2026-08-24",
    cutoffHistory: [
      { year: 2024, cutoff: 34.800, figureType: "last_admitted", sourceTier: "university_official" },
      { year: 2024, cutoff: 36.700, figureType: "average", sourceTier: "university_official" },
    ],
    prerequisites: [
      { name: "Calculus 1 & 2 (201-NYA / 201-NYB)", status: "met" },
      { name: "General Chemistry & Solutions (202-NYA / 202-NYB)", status: "met" },
      { name: "Physics 1, 2, 3 (203-NYA / 203-NYB / 203-NYC)", status: "met" },
      { name: "General Biology (101-NYA)", status: "met" },
    ],
  },
  {
    id: "sherbrooke-medecine",
    name: "Doctorat de 1er cycle en médecine (MD)",
    institution: "Université de Sherbrooke",
    description: "Formation médicale axée sur l'apprentissage par problèmes (APP), l'interdisciplinarité et la pratique en régions.",
    interestIds: ["health", "science"],
    cohortLabel: "Cohorte automne 2026",
    placementRate: { value: 100, note: "Accès à la résidence." },
    professionalOrders: { codes: ["CMQ"], note: "Collège des médecins du Québec." },
    sourceUrl: "https://www.usherbrooke.ca/admission/programme/605/doctorat-en-medecine",
    lastVerifiedAt: "2026-08-24",
    cutoffHistory: [
      { year: 2024, cutoff: 33.400, figureType: "last_admitted", sourceTier: "university_official" },
      { year: 2024, cutoff: 35.400, figureType: "average", sourceTier: "university_official" },
    ],
    prerequisites: [
      { name: "Calcul différentiel (201-NYA)", status: "met" },
      { name: "Chimie générale (202-NYA)", status: "met" },
      { name: "Chimie des solutions (202-NYB)", status: "met" },
      { name: "Physique (203-NYA, 203-NYB, 203-NYC)", status: "met" },
      { name: "Biologie (101-NYA)", status: "met" },
    ],
  },
  {
    id: "udem-pharmacie",
    name: "Doctorat de 1er cycle en pharmacie (Pharm. D.)",
    institution: "Université de Montréal",
    description: "Formation professionnelle clinique préparant à la pratique de pharmacien en milieu communautaire ou hospitalier.",
    interestIds: ["health", "science"],
    cohortLabel: "Cohorte automne 2026",
    placementRate: { value: 99, note: "Pleine employabilité dès l'obtention du permis de l'OPQ." },
    professionalOrders: { codes: ["OPQ"], note: "Ordre des pharmaciens du Québec." },
    sourceUrl: "https://admission.umontreal.ca/programmes/doctorat-de-1er-cycle-en-pharmacie/",
    lastVerifiedAt: "2026-08-24",
    cutoffHistory: [
      { year: 2024, cutoff: 33.050, figureType: "last_admitted", sourceTier: "university_official" },
      { year: 2024, cutoff: 34.800, figureType: "average", sourceTier: "university_official" },
    ],
    prerequisites: [
      { name: "Calcul 1 et 2 (201-NYA, 201-NYB)", status: "met" },
      { name: "Chimie générale et des solutions (202-NYA, 202-NYB)", status: "met" },
      { name: "Physique mécanique et électricité (203-NYA, 203-NYB)", status: "met" },
      { name: "Biologie générale (101-NYA)", status: "met" },
    ],
  },
  {
    id: "ulaval-pharmacie",
    name: "Doctorat de 1er cycle en pharmacie (Pharm. D.)",
    institution: "Université Laval",
    description: "Doctorat de 1er cycle intégrant pharmacologie, chimie pharmaceutique, soins pharmaceutiques et stages cliniques en milieu hospitalier et communautaire.",
    interestIds: ["health", "science"],
    cohortLabel: "Cohorte automne 2026",
    placementRate: { value: 99, note: "En emploi ou poursuite en résidence hospitalière." },
    professionalOrders: { codes: ["OPQ"], note: "Ordre des pharmaciens du Québec." },
    sourceUrl: "https://www.ulaval.ca/etudes/programmes/doctorat-de-1er-cycle-en-pharmacie",
    lastVerifiedAt: "2026-08-24",
    cutoffHistory: [
      { year: 2024, cutoff: 32.800, figureType: "last_admitted", sourceTier: "university_official" },
      { year: 2024, cutoff: 34.500, figureType: "average", sourceTier: "university_official" },
    ],
    prerequisites: [
      { name: "Calcul différentiel (201-NYA)", status: "met" },
      { name: "Chimie générale et solutions (202-NYA, 202-NYB)", status: "met" },
      { name: "Physique 1, 2, 3 (203-NYA, 203-NYB, 203-NYC)", status: "met" },
      { name: "Biologie générale (101-NYA)", status: "met" },
    ],
  },
  {
    id: "udem-dentaire",
    name: "Doctorat de 1er cycle en médecine dentaire (DMD)",
    institution: "Université de Montréal",
    description: "Formation de dentiste clinicien avec clinique universitaire moderne et laboratoires de simulation préclinique.",
    interestIds: ["health", "science"],
    cohortLabel: "Cohorte automne 2026",
    placementRate: { value: 100, note: "Pratique en clinique privée, hôpitaux ou spécialités." },
    professionalOrders: { codes: ["ODQ"], note: "Ordre des dentistes du Québec." },
    sourceUrl: "https://admission.umontreal.ca/programmes/doctorat-de-1er-cycle-en-medecine-dentaire/",
    lastVerifiedAt: "2026-08-24",
    cutoffHistory: [
      { year: 2024, cutoff: 33.600, figureType: "last_admitted", sourceTier: "university_official" },
      { year: 2024, cutoff: 35.500, figureType: "average", sourceTier: "university_official" },
    ],
    prerequisites: [
      { name: "Calcul 1 et 2 (201-NYA, 201-NYB)", status: "met" },
      { name: "Chimie générale et solutions (202-NYA, 202-NYB)", status: "met" },
      { name: "Physique (203-NYA, 203-NYB, 203-NYC)", status: "met" },
      { name: "Biologie (101-NYA, 101-HTK)", status: "met" },
    ],
  },
  {
    id: "ulaval-dentaire",
    name: "Doctorat de 1er cycle en médecine dentaire (DMD)",
    institution: "Université Laval",
    description: "Doctorat en médecine dentaire combinant sciences biomédicales, techniques opératoires et soins aux patients à la clinique dentaire.",
    interestIds: ["health", "science"],
    cohortLabel: "Cohorte automne 2026",
    placementRate: { value: 100, note: "Pratique générale ou spécialisation." },
    professionalOrders: { codes: ["ODQ"], note: "Ordre des dentistes du Québec." },
    sourceUrl: "https://www.ulaval.ca/etudes/programmes/doctorat-de-1er-cycle-en-medecine-dentaire",
    lastVerifiedAt: "2026-08-24",
    cutoffHistory: [
      { year: 2024, cutoff: 33.200, figureType: "last_admitted", sourceTier: "university_official" },
    ],
    prerequisites: [
      { name: "Calcul différentiel (201-NYA)", status: "met" },
      { name: "Chimie des solutions (202-NYB)", status: "met" },
      { name: "Physique 1, 2, 3 (203-NYA, 203-NYB, 203-NYC)", status: "met" },
      { name: "Biologie 1 (101-NYA)", status: "met" },
    ],
  },
  {
    id: "udem-physiotherapie",
    name: "Baccalauréat en physiothérapie",
    institution: "Université de Montréal",
    description: "Premier cycle du continuum baccalauréat-maîtrise professionnelle menant à l'exercice de la physiothérapie.",
    interestIds: ["health", "science"],
    cohortLabel: "Cohorte automne 2026",
    placementRate: { value: 98, note: "Accès à la maîtrise professionnelle obligatoire pour la pratique." },
    professionalOrders: { codes: ["OPPQ"], note: "Ordre professionnel de la physiothérapie du Québec." },
    sourceUrl: "https://admission.umontreal.ca/programmes/baccalaureat-en-physiotherapie/",
    lastVerifiedAt: "2026-08-24",
    cutoffHistory: [
      { year: 2024, cutoff: 32.100, figureType: "last_admitted", sourceTier: "university_official" },
      { year: 2024, cutoff: 33.700, figureType: "average", sourceTier: "university_official" },
    ],
    prerequisites: [
      { name: "Calcul différentiel (201-NYA)", status: "met" },
      { name: "Chimie générale et solutions (202-NYA, 202-NYB)", status: "met" },
      { name: "Physique 1, 2, 3 (203-NYA, 203-NYB, 203-NYC)", status: "met" },
      { name: "Biologie générale (101-NYA)", status: "met" },
    ],
  },
  {
    id: "udem-optometrie",
    name: "Doctorat de 1er cycle en optométrie (O.D.)",
    institution: "Université de Montréal",
    description: "Unique programme d'optométrie francophone au Canada, dispensé à l'École d'optométrie de l'UdeM.",
    interestIds: ["health", "science"],
    cohortLabel: "Cohorte automne 2026",
    placementRate: { value: 100, note: "Pleine employabilité clinique." },
    professionalOrders: { codes: ["OOQ"], note: "Ordre des optométristes du Québec." },
    sourceUrl: "https://admission.umontreal.ca/programmes/doctorat-de-1er-cycle-en-optometrie/",
    lastVerifiedAt: "2026-08-24",
    cutoffHistory: [
      { year: 2024, cutoff: 33.300, figureType: "last_admitted", sourceTier: "university_official" },
      { year: 2024, cutoff: 35.100, figureType: "average", sourceTier: "university_official" },
    ],
    prerequisites: [
      { name: "Calcul 1 et 2 (201-NYA, 201-NYB)", status: "met" },
      { name: "Chimie générale et des solutions (202-NYA, 202-NYB)", status: "met" },
      { name: "Physique mécanique, électricité, ondes (203-NYA, 203-NYB, 203-NYC)", status: "met" },
      { name: "Biologie 1 et 2 (101-NYA, 101-HTK)", status: "met" },
    ],
  },
  {
    id: "udem-veterinaire",
    name: "Doctorat de 1er cycle en médecine vétérinaire (DMV)",
    institution: "Université de Montréal (Saint-Hyacinthe)",
    description: "Unique faculté de médecine vétérinaire au Québec, située à Saint-Hyacinthe avec hôpital vétérinaire universitaire.",
    interestIds: ["health", "science", "environment"],
    cohortLabel: "Cohorte automne 2026",
    placementRate: { value: 99, note: "Animaux de compagnie, animaux de rente et santé publique." },
    professionalOrders: { codes: ["OMVQ"], note: "Ordre des médecins vétérinaires du Québec." },
    sourceUrl: "https://admission.umontreal.ca/programmes/doctorat-de-1er-cycle-en-medecine-veterinaire/",
    lastVerifiedAt: "2026-08-24",
    cutoffHistory: [
      { year: 2024, cutoff: 34.000, figureType: "last_admitted", sourceTier: "university_official" },
      { year: 2024, cutoff: 35.900, figureType: "average", sourceTier: "university_official" },
    ],
    prerequisites: [
      { name: "Calcul différentiel et intégral (201-NYA, 201-NYB)", status: "met" },
      { name: "Chimie générale et des solutions (202-NYA, 202-NYB)", status: "met" },
      { name: "Physique (203-NYA, 203-NYB, 203-NYC)", status: "met" },
      { name: "Biologie générale (101-NYA, 101-HTK)", status: "met" },
    ],
  },
  {
    id: "laval-sciences-infirmieres",
    name: "Sciences infirmières",
    institution: "Université Laval",
    description: "Formation clinique menant à l'exercice infirmier, avec stages en milieu hospitalier dès la première année.",
    interestIds: ["health"],
    cohortLabel: "Cohorte automne 2026",
    placementRate: { value: 98, note: "Pleine employabilité dans le réseau de la santé du Québec." },
    professionalOrders: { codes: ["OIIQ"], note: "L'exercice infirmier au Québec est réservé aux membres de l'Ordre." },
    sourceUrl: "https://www.ulaval.ca/sites/default/files/futurs-etudiants/IPC_2024-2025-WEB.pdf",
    lastVerifiedAt: "2026-08-24",
    cutoffHistory: [
      { year: 2023, cutoff: 26.529, figureType: "last_admitted", sourceTier: "university_official" },
    ],
    prerequisites: [
      { name: "Biologie humaine / générale", status: "met" },
    ],
  },
  {
    id: "udem-sciences-infirmieres",
    name: "Baccalauréat en sciences infirmières",
    institution: "Université de Montréal",
    description: "Formation infirmière de pointe reconnue par l'OIIQ, axée sur les soins critiques, communautaires et la gestion clinique.",
    interestIds: ["health"],
    cohortLabel: "Cohorte automne 2026",
    placementRate: { value: 99, note: "Emploi garanti dans le réseau de santé québécois." },
    professionalOrders: { codes: ["OIIQ"], note: "Ordre des infirmières et infirmiers du Québec." },
    sourceUrl: "https://admission.umontreal.ca/programmes/baccalaureat-en-sciences-infirmieres/",
    lastVerifiedAt: "2026-08-24",
    cutoffHistory: [
      { year: 2024, cutoff: 26.100, figureType: "last_admitted", sourceTier: "university_official" },
      { year: 2024, cutoff: 28.500, figureType: "average", sourceTier: "university_official" },
    ],
    prerequisites: [],
  },

  // --- DROIT & SCIENCES JURIDIQUES ---
  {
    id: "udem-droit",
    name: "Droit (LL.B.)",
    institution: "Université de Montréal",
    description: "Baccalauréat en droit civil québécois, menant au Barreau ou à la Chambre des notaires après la formation professionnelle.",
    interestIds: ["law_social"],
    cohortLabel: "Cohorte automne 2026",
    placementRate: { value: 92, note: "Poursuite à l'École du Barreau ou aux cycles supérieurs." },
    professionalOrders: { codes: ["Barreau", "Notaires"], note: "Ordres professionnels accessibles après la formation professionnelle requise." },
    sourceUrl: "https://admission.umontreal.ca/statistiques-dadmission-cote-r/",
    lastVerifiedAt: "2026-08-24",
    cutoffHistory: [
      { year: 2024, cutoff: 31.505, figureType: "last_admitted", sourceTier: "university_official" },
      { year: 2024, cutoff: 33.168, figureType: "average", sourceTier: "university_official" },
      { year: 2024, cutoff: 38.058, figureType: "maximum", sourceTier: "university_official" },
    ],
    prerequisites: [],
  },
  {
    id: "ulaval-droit",
    name: "Baccalauréat en droit",
    institution: "Université Laval",
    description: "Faculté de droit historique du Québec, offrant formation en droit civil, droit des affaires, droit public et international.",
    interestIds: ["law_social"],
    cohortLabel: "Cohorte automne 2026",
    placementRate: { value: 93, note: "Barreau, Notariat, fonction publique et contentieux d'affaires." },
    professionalOrders: { codes: ["Barreau", "Notaires"], note: "Accès aux examens du Barreau du Québec." },
    sourceUrl: "https://www.ulaval.ca/etudes/programmes/baccalaureat-en-droit",
    lastVerifiedAt: "2026-08-24",
    cutoffHistory: [
      { year: 2024, cutoff: 29.800, figureType: "last_admitted", sourceTier: "university_official" },
      { year: 2024, cutoff: 31.900, figureType: "average", sourceTier: "university_official" },
    ],
    prerequisites: [],
  },
  {
    id: "mcgill-law",
    name: "Bachelor of Civil Law and Juris Doctor (BCL/JD)",
    institution: "McGill University",
    description: "Unique integrated bilingual program teaching both Civil Law and Common Law systems.",
    interestIds: ["law_social"],
    cohortLabel: "Cohorte automne 2026",
    placementRate: { value: 95, note: "Global legal practice and judicial clerkships." },
    professionalOrders: { codes: ["Barreau", "Law Society"], note: "Eligible for Barreau du Québec and provincial Law Societies." },
    sourceUrl: "https://www.mcgill.ca/law/admissions",
    lastVerifiedAt: "2026-08-24",
    cutoffHistory: [
      { year: 2024, cutoff: 33.000, figureType: "last_admitted", sourceTier: "university_official" },
      { year: 2024, cutoff: 34.800, figureType: "average", sourceTier: "university_official" },
    ],
    prerequisites: [],
  },
  {
    id: "sherbrooke-droit",
    name: "Baccalauréat en droit (LL.B.)",
    institution: "Université de Sherbrooke",
    description: "Formation juridique axée sur la pratique, le droit de l'entreprise, les technologies et le cheminement intégré Droit-MBA.",
    interestIds: ["law_social", "business"],
    cohortLabel: "Cohorte automne 2026",
    placementRate: { value: 94, note: "Cabinet d'avocats, magistrature, entreprises." },
    professionalOrders: { codes: ["Barreau", "Notaires"], note: "Barreau du Québec et Chambre des notaires." },
    sourceUrl: "https://www.usherbrooke.ca/admission/programme/215/baccalaureat-en-droit",
    lastVerifiedAt: "2026-08-24",
    cutoffHistory: [
      { year: 2024, cutoff: 29.500, figureType: "last_admitted", sourceTier: "university_official" },
      { year: 2024, cutoff: 31.400, figureType: "average", sourceTier: "university_official" },
    ],
    prerequisites: [],
  },
  {
    id: "uqam-droit",
    name: "Baccalauréat en sciences juridiques (droit)",
    institution: "Université du Québec à Montréal (UQAM)",
    description: "Programme de droit reconnu pour son engagement social, le droit du travail, les droits de la personne et la justice sociale.",
    interestIds: ["law_social"],
    cohortLabel: "Cohorte automne 2026",
    placementRate: { value: 91, note: "Barreau du Québec et contentieux juridique." },
    professionalOrders: { codes: ["Barreau", "Notaires"], note: "Accès à l'École du Barreau." },
    sourceUrl: "https://etudier.uqam.ca/programme/baccalaureat-sciences-juridiques",
    lastVerifiedAt: "2026-08-24",
    cutoffHistory: [
      { year: 2024, cutoff: 29.100, figureType: "last_admitted", sourceTier: "university_official" },
      { year: 2024, cutoff: 31.000, figureType: "average", sourceTier: "university_official" },
    ],
    prerequisites: [],
  },

  // --- GÉNIE & INFORMATIQUE ---
  {
    id: "poly-genie-logiciel",
    name: "Génie logiciel",
    institution: "Polytechnique Montréal",
    description: "Formation d'ingénieur agréée couvrant la conception, l'architecture et la vérification des systèmes logiciels à grande échelle.",
    interestIds: ["tech_eng"],
    cohortLabel: "Cohorte automne 2026",
    placementRate: { value: 96, note: "En emploi ou aux études supérieures dans les 6 mois suivant la diplomation." },
    professionalOrders: { codes: ["OIQ"], note: "Le titre d'ingénieur au Québec est réservé et encadré par l'Ordre des ingénieurs." },
    sourceUrl: "https://www.polymtl.ca/etudes/bacc/logiciel",
    lastVerifiedAt: "2026-08-24",
    cutoffHistory: [
      { year: 2024, cutoff: 28.500, figureType: "last_admitted", sourceTier: "university_official" },
      { year: 2024, cutoff: 31.200, figureType: "average", sourceTier: "university_official" },
    ],
    prerequisites: [
      { name: "Calcul différentiel (201-NYA)", status: "met" },
      { name: "Calcul intégral (201-NYB)", status: "met" },
      { name: "Algèbre linéaire (201-NYC)", status: "met" },
      { name: "Physique : Mécanique (203-NYA)", status: "met" },
      { name: "Physique : Électricité (203-NYB)", status: "met" },
      { name: "Chimie générale (202-NYA)", status: "met" },
    ],
  },
  {
    id: "ulaval-genie-logiciel",
    name: "Baccalauréat en génie logiciel",
    institution: "Université Laval",
    description: "Formation d'ingénieur logiciel agréée avec volet coopératif (stages rémunérés) et projets industriels réels.",
    interestIds: ["tech_eng"],
    cohortLabel: "Cohorte automne 2026",
    placementRate: { value: 97, note: "Très forte demande dans l'industrie tech et du jeu vidéo." },
    professionalOrders: { codes: ["OIQ"], note: "Ordre des ingénieurs du Québec." },
    sourceUrl: "https://www.ulaval.ca/etudes/programmes/baccalaureat-en-genie-logiciel",
    lastVerifiedAt: "2026-08-24",
    cutoffHistory: [
      { year: 2024, cutoff: 26.500, figureType: "last_admitted", sourceTier: "university_official" },
    ],
    prerequisites: [
      { name: "Calcul différentiel (201-NYA)", status: "met" },
      { name: "Calcul intégral (201-NYB)", status: "met" },
      { name: "Algèbre linéaire (201-NYC)", status: "met" },
      { name: "Physique (203-NYA, 203-NYB)", status: "met" },
      { name: "Chimie (202-NYA)", status: "met" },
    ],
  },
  {
    id: "ets-genie-logiciel",
    name: "Baccalauréat en génie logiciel",
    institution: "École de technologie supérieure (ÉTS)",
    description: "Programme de génie logiciel axé sur la pratique industrielle, comportant 3 stages rémunérés obligatoires intégrés au cursus.",
    interestIds: ["tech_eng"],
    cohortLabel: "Cohorte automne 2026",
    placementRate: { value: 98, note: "Pleine employabilité industrielle avec 3 stages rémunérés." },
    professionalOrders: { codes: ["OIQ"], note: "Ordre des ingénieurs du Québec." },
    sourceUrl: "https://www.etsmtl.ca/etude/baccalaureat/genie-logiciel",
    lastVerifiedAt: "2026-08-24",
    cutoffHistory: [
      { year: 2024, cutoff: 24.500, figureType: "last_admitted", sourceTier: "university_official" },
    ],
    prerequisites: [
      { name: "DEC technique ou DEC sciences de la nature avec cours passerelle", status: "met" },
    ],
  },
  {
    id: "sherbrooke-genie-logiciel",
    name: "Baccalauréat en génie logiciel (coopératif)",
    institution: "Université de Sherbrooke",
    description: "Programme en régime coopératif alternant sessions d'études et 4 à 5 stages rémunérés en entreprise.",
    interestIds: ["tech_eng"],
    cohortLabel: "Cohorte automne 2026",
    placementRate: { value: 99, note: "Embauche avant même la diplomation via les stages coop." },
    professionalOrders: { codes: ["OIQ"], note: "Ordre des ingénieurs du Québec." },
    sourceUrl: "https://www.usherbrooke.ca/admission/programme/280/baccalaureat-en-genie-logiciel",
    lastVerifiedAt: "2026-08-24",
    cutoffHistory: [
      { year: 2024, cutoff: 27.200, figureType: "last_admitted", sourceTier: "university_official" },
    ],
    prerequisites: [
      { name: "Calcul différentiel (201-NYA)", status: "met" },
      { name: "Calcul intégral (201-NYB)", status: "met" },
      { name: "Algèbre linéaire (201-NYC)", status: "met" },
      { name: "Physique (203-NYA, 203-NYB, 203-NYC)", status: "met" },
      { name: "Chimie (202-NYA)", status: "met" },
    ],
  },
  {
    id: "concordia-software-eng",
    name: "Bachelor of Engineering in Software Engineering",
    institution: "Concordia University",
    description: "Gina Cody School of Engineering accredited program focusing on software architecture, distributed systems and cloud engineering.",
    interestIds: ["tech_eng"],
    cohortLabel: "Cohorte automne 2026",
    placementRate: { value: 95, note: "High tech and software industry placement." },
    professionalOrders: { codes: ["OIQ", "Engineers Canada"], note: "Accredited engineering degree." },
    sourceUrl: "https://www.concordia.ca/ginacody/computer-science-software-eng/programs/software-engineering-beng.html",
    lastVerifiedAt: "2026-08-24",
    cutoffHistory: [
      { year: 2024, cutoff: 27.000, figureType: "last_admitted", sourceTier: "university_official" },
    ],
    prerequisites: [
      { name: "Calculus 1 & 2", status: "met" },
      { name: "Linear Algebra", status: "met" },
      { name: "Physics: Mechanics & E&M", status: "met" },
      { name: "Chemistry 1", status: "met" },
    ],
  },
  {
    id: "mcgill-computer-science",
    name: "Bachelor of Science in Computer Science",
    institution: "McGill University",
    description: "World-class computer science program covering algorithms, artificial intelligence (Mila affiliation), systems, and data science.",
    interestIds: ["tech_eng", "science"],
    cohortLabel: "Cohorte automne 2026",
    placementRate: { value: 96, note: "AI research and top tech firms worldwide." },
    sourceUrl: "https://www.cs.mcgill.ca/academic/undergrad/",
    lastVerifiedAt: "2026-08-24",
    cutoffHistory: [
      { year: 2024, cutoff: 31.000, figureType: "last_admitted", sourceTier: "university_official" },
      { year: 2024, cutoff: 33.200, figureType: "average", sourceTier: "university_official" },
    ],
    prerequisites: [
      { name: "Calculus 1 & 2 (201-NYA, 201-NYB)", status: "met" },
      { name: "Linear Algebra (201-NYC)", status: "met" },
    ],
  },
  {
    id: "udem-informatique",
    name: "Baccalauréat en informatique",
    institution: "Université de Montréal",
    description: "Programme de pointe en informatique fondamentale et intelligence artificielle en lien étroit avec Mila (Institut québécois d'IA).",
    interestIds: ["tech_eng", "science"],
    cohortLabel: "Cohorte automne 2026",
    placementRate: { value: 95, note: "Développement logiciel et recherche en IA." },
    sourceUrl: "https://admission.umontreal.ca/programmes/baccalaureat-en-informatique/",
    lastVerifiedAt: "2026-08-24",
    cutoffHistory: [
      { year: 2024, cutoff: 26.800, figureType: "last_admitted", sourceTier: "university_official" },
      { year: 2024, cutoff: 29.500, figureType: "average", sourceTier: "university_official" },
    ],
    prerequisites: [
      { name: "Calcul différentiel (201-NYA)", status: "met" },
      { name: "Calcul intégral (201-NYB)", status: "met" },
      { name: "Algèbre linéaire (201-NYC)", status: "met" },
    ],
  },
  {
    id: "laval-genie-civil",
    name: "Génie civil",
    institution: "Université Laval",
    description: "Conception et gestion des infrastructures : structures, transport, ressources hydriques et géotechnique.",
    interestIds: ["tech_eng", "environment"],
    cohortLabel: "Cohorte automne 2026",
    professionalOrders: { codes: ["OIQ"], note: "Le titre d'ingénieur au Québec est réservé et encadré par l'Ordre des ingénieurs." },
    sourceUrl: "https://www.ulaval.ca/etudes/programmes/baccalaureat-en-genie-civil",
    lastVerifiedAt: "2026-08-24",
    cutoffHistory: [
      { year: 2024, cutoff: 25.000, figureType: "last_admitted", sourceTier: "university_official" },
    ],
    prerequisites: [
      { name: "Calcul différentiel (201-NYA)", status: "met" },
      { name: "Calcul intégral (201-NYB)", status: "met" },
      { name: "Algèbre linéaire (201-NYC)", status: "met" },
      { name: "Physique (203-NYA, 203-NYB)", status: "met" },
      { name: "Chimie (202-NYA)", status: "met" },
    ],
  },
  {
    id: "poly-genie-mecanique",
    name: "Baccalauréat en génie mécanique",
    institution: "Polytechnique Montréal",
    description: "Formation d'ingénieur mécanique couvrant la conception mécanique, la mécatronique, la thermodynamique et la fabrication avancée.",
    interestIds: ["tech_eng"],
    cohortLabel: "Cohorte automne 2026",
    placementRate: { value: 95, note: "Automobile, aéronautique, énergie et robotique." },
    professionalOrders: { codes: ["OIQ"], note: "Ordre des ingénieurs du Québec." },
    sourceUrl: "https://www.polymtl.ca/etudes/bacc/mecanique",
    lastVerifiedAt: "2026-08-24",
    cutoffHistory: [
      { year: 2024, cutoff: 27.500, figureType: "last_admitted", sourceTier: "university_official" },
    ],
    prerequisites: [
      { name: "Calcul 1 et 2 (201-NYA, 201-NYB)", status: "met" },
      { name: "Algèbre linéaire (201-NYC)", status: "met" },
      { name: "Physique (203-NYA, 203-NYB, 203-NYC)", status: "met" },
      { name: "Chimie générale (202-NYA)", status: "met" },
    ],
  },
  {
    id: "poly-genie-aerospatial",
    name: "Baccalauréat en génie aérospatial",
    institution: "Polytechnique Montréal",
    description: "Programme hautement contingenté en conception d'aéronefs, avionique, propulsion spatiale et systèmes de satellites.",
    interestIds: ["tech_eng", "science"],
    cohortLabel: "Cohorte automne 2026",
    placementRate: { value: 97, note: "Secteur aérospatial québécois et international (Bombardier, CAE, Pratt & Whitney, NASA/CSA)." },
    professionalOrders: { codes: ["OIQ"], note: "Ordre des ingénieurs du Québec." },
    sourceUrl: "https://www.polymtl.ca/etudes/bacc/aerospatial",
    lastVerifiedAt: "2026-08-24",
    cutoffHistory: [
      { year: 2024, cutoff: 31.000, figureType: "last_admitted", sourceTier: "university_official" },
      { year: 2024, cutoff: 33.200, figureType: "average", sourceTier: "university_official" },
    ],
    prerequisites: [
      { name: "Calcul différentiel et intégral (201-NYA, 201-NYB)", status: "met" },
      { name: "Algèbre linéaire (201-NYC)", status: "met" },
      { name: "Physique (203-NYA, 203-NYB, 203-NYC)", status: "met" },
      { name: "Chimie générale (202-NYA)", status: "met" },
    ],
  },

  // --- GESTION & AFFAIRES ---
  {
    id: "hec-baa",
    name: "Administration des affaires (BAA)",
    institution: "HEC Montréal",
    description: "Programme reconnu internationalement, alliant la théorie de gestion rigoureuse à la pratique, préparant à des rôles de direction dans un contexte mondial.",
    interestIds: ["business"],
    cohortLabel: "Cohorte automne 2026",
    placementRate: { value: 96, note: "En emploi ou aux études supérieures dans les 6 mois suivant la diplomation." },
    professionalOrders: { codes: ["CPA", "CRHA", "CFA"], note: "Ordres et titres professionnels que rejoignent couramment les diplômés du BAA." },
    sourceUrl: "https://www.hec.ca/programmes/baccalaureats/baa/demande-admission",
    lastVerifiedAt: "2026-08-24",
    cutoffHistory: [
      { year: 2024, cutoff: 27.500, figureType: "last_admitted", sourceTier: "university_official" },
      { year: 2024, cutoff: 29.800, figureType: "average", sourceTier: "university_official" },
    ],
    prerequisites: [
      { name: "Calcul différentiel (201-NYA ou 201-MA1)", status: "met" },
      { name: "Calcul intégral (201-NYB ou 201-MA2)", status: "met" },
      { name: "Algèbre linéaire (201-NYC ou 201-MA3)", status: "met" },
    ],
  },
  {
    id: "ulaval-baa",
    name: "Baccalauréat en administration des affaires (B.A.A.)",
    institution: "Université Laval",
    description: "Faculté des sciences de l'administration (FSA ULaval) accréditée AACSB et EQUIS, offrant des spécialisations en finance, comptabilité, marketing et gestion.",
    interestIds: ["business"],
    cohortLabel: "Cohorte automne 2026",
    placementRate: { value: 95, note: "En emploi ou en démarrage d'entreprise." },
    professionalOrders: { codes: ["CPA", "CRHA"], note: "Ordre des CPA du Québec et Ordre des CRHA." },
    sourceUrl: "https://www.ulaval.ca/etudes/programmes/baccalaureat-en-administration-des-affaires",
    lastVerifiedAt: "2026-08-24",
    cutoffHistory: [
      { year: 2024, cutoff: 25.000, figureType: "last_admitted", sourceTier: "university_official" },
    ],
    prerequisites: [
      { name: "Calcul différentiel ou Mathématiques d'administration", status: "met" },
    ],
  },
  {
    id: "concordia-jmsb-bcomm",
    name: "Bachelor of Commerce (BComm - John Molson)",
    institution: "Concordia University",
    description: "AACSB-accredited business school offering majors in Finance, Accountancy, Marketing, Supply Chain, and Business Technology Management.",
    interestIds: ["business"],
    cohortLabel: "Cohorte automne 2026",
    placementRate: { value: 94, note: "Corporate banking, consulting, and multinational management." },
    professionalOrders: { codes: ["CPA", "CFA"], note: "CPA and CFA charter paths." },
    sourceUrl: "https://www.concordia.ca/jmsb/programs/undergraduate/bachelor.html",
    lastVerifiedAt: "2026-08-24",
    cutoffHistory: [
      { year: 2024, cutoff: 27.000, figureType: "last_admitted", sourceTier: "university_official" },
      { year: 2024, cutoff: 29.000, figureType: "average", sourceTier: "university_official" },
    ],
    prerequisites: [
      { name: "Calculus 1 (201-NYA)", status: "met" },
      { name: "Linear Algebra (201-NYC)", status: "met" },
    ],
  },
  {
    id: "mcgill-bcom",
    name: "Bachelor of Commerce (BCom - Desautels)",
    institution: "McGill University",
    description: "Top-ranked global business program with honours streams in Investment Management and Economics.",
    interestIds: ["business"],
    cohortLabel: "Cohorte automne 2026",
    placementRate: { value: 96, note: "Global finance, investment banking, and management consulting." },
    professionalOrders: { codes: ["CPA", "CFA"], note: "Professional designations." },
    sourceUrl: "https://www.mcgill.ca/desautels/programs/bcom",
    lastVerifiedAt: "2026-08-24",
    cutoffHistory: [
      { year: 2024, cutoff: 29.500, figureType: "last_admitted", sourceTier: "university_official" },
      { year: 2024, cutoff: 31.800, figureType: "average", sourceTier: "university_official" },
    ],
    prerequisites: [
      { name: "Calculus 1 & 2 (201-NYA, 201-NYB)", status: "met" },
      { name: "Linear Algebra (201-NYC)", status: "met" },
    ],
  },

  // --- SCIENCES PURES, APPLIQUÉES & ENVIRONNEMENT ---
  {
    id: "laval-sciences-bio",
    name: "Sciences biologiques",
    institution: "Université Laval",
    description: "Étude du vivant, de la génétique aux écosystèmes, avec une forte composante de laboratoire et de terrain.",
    interestIds: ["science", "environment"],
    cohortLabel: "Cohorte automne 2026",
    sourceUrl: "https://www.ulaval.ca/etudes/programmes/baccalaureat-en-biologie",
    lastVerifiedAt: "2026-08-24",
    cutoffHistory: [
      { year: 2024, cutoff: 24.000, figureType: "minimum_required", sourceTier: "university_official" },
    ],
    prerequisites: [
      { name: "Chimie générale (202-NYA)", status: "met" },
      { name: "Biologie générale (101-NYA)", status: "met" },
    ],
  },
  {
    id: "udem-actuariat",
    name: "Baccalauréat en actuariat",
    institution: "Université de Montréal",
    description: "Formation mathématique et statistique de haut niveau préparant aux examens professionnels de la Society of Actuaries (SOA) et de l'Institut canadien des actuaires (ICA).",
    interestIds: ["science", "business"],
    cohortLabel: "Cohorte automne 2026",
    placementRate: { value: 99, note: "Pleine employabilité en assurance, finance quantitative et gestion des risques." },
    professionalOrders: { codes: ["ICA", "SOA"], note: "Institut canadien des actuaires." },
    sourceUrl: "https://admission.umontreal.ca/programmes/baccalaureat-en-actuariat/",
    lastVerifiedAt: "2026-08-24",
    cutoffHistory: [
      { year: 2024, cutoff: 30.200, figureType: "last_admitted", sourceTier: "university_official" },
      { year: 2024, cutoff: 32.500, figureType: "average", sourceTier: "university_official" },
    ],
    prerequisites: [
      { name: "Calcul différentiel (201-NYA)", status: "met" },
      { name: "Calcul intégral (201-NYB)", status: "met" },
      { name: "Algèbre linéaire (201-NYC)", status: "met" },
    ],
  },
  {
    id: "ulaval-actuariat",
    name: "Baccalauréat en actuariat",
    institution: "Université Laval",
    description: "L'un des centres d'excellence actuarielle les plus réputés en Amérique du Nord (Centre of Actuarial Excellence).",
    interestIds: ["science", "business"],
    cohortLabel: "Cohorte automne 2026",
    placementRate: { value: 98, note: "Compagnies d'assurances, caisses de retraite et institutions financières." },
    professionalOrders: { codes: ["ICA", "SOA"], note: "Institut canadien des actuaires." },
    sourceUrl: "https://www.ulaval.ca/etudes/programmes/baccalaureat-en-actuariat",
    lastVerifiedAt: "2026-08-24",
    cutoffHistory: [
      { year: 2024, cutoff: 28.500, figureType: "last_admitted", sourceTier: "university_official" },
      { year: 2024, cutoff: 31.000, figureType: "average", sourceTier: "university_official" },
    ],
    prerequisites: [
      { name: "Calcul différentiel et intégral (201-NYA, 201-NYB)", status: "met" },
      { name: "Algèbre linéaire (201-NYC)", status: "met" },
    ],
  },
  {
    id: "ulaval-architecture",
    name: "Baccalauréat en sciences de l'architecture",
    institution: "Université Laval",
    description: "École d'architecture située au cœur du Vieux-Québec, dispensant une formation reconnue sur le patrimoine, la conception durable et le design spatial.",
    interestIds: ["arts_comm", "tech_eng"],
    cohortLabel: "Cohorte automne 2026",
    placementRate: { value: 94, note: "Poursuite vers la maîtrise professionnelle en architecture." },
    professionalOrders: { codes: ["OAQ"], note: "Ordre des architectes du Québec (après maîtrise)." },
    sourceUrl: "https://www.ulaval.ca/etudes/programmes/baccalaureat-en-sciences-de-larchitecture",
    lastVerifiedAt: "2026-08-24",
    cutoffHistory: [
      { year: 2024, cutoff: 28.000, figureType: "last_admitted", sourceTier: "university_official" },
    ],
    prerequisites: [
      { name: "Physique : Mécanique (203-NYA)", status: "met" },
      { name: "Mathématiques collégiales", status: "met" },
    ],
  },

  // --- SCIENCES HUMAINES, SOCIALES & ÉDUCATION ---
  {
    id: "udem-psychologie",
    name: "Baccalauréat en psychologie",
    institution: "Université de Montréal",
    description: "Étude des processus cognitifs, du développement humain, de la neuropsychologie et de la santé mentale.",
    interestIds: ["law_social", "health"],
    cohortLabel: "Cohorte automne 2026",
    placementRate: { value: 90, note: "Accès au doctorat professionnel (D.Psy) pour devenir psychologue." },
    professionalOrders: { codes: ["OPQ"], note: "Ordre des psychologues du Québec (après doctorat)." },
    sourceUrl: "https://admission.umontreal.ca/programmes/baccalaureat-en-psychologie/",
    lastVerifiedAt: "2026-08-24",
    cutoffHistory: [
      { year: 2024, cutoff: 28.500, figureType: "last_admitted", sourceTier: "university_official" },
      { year: 2024, cutoff: 31.000, figureType: "average", sourceTier: "university_official" },
    ],
    prerequisites: [
      { name: "Méthodes quantitatives ou Calcul différentiel", status: "met" },
      { name: "Biologie humaine", status: "met" },
    ],
  },
  {
    id: "ulaval-psychologie",
    name: "Baccalauréat en psychologie",
    institution: "Université Laval",
    description: "Formation scientifique couvrant la psychologie clinique, cognitive, sociale et la neuropsychologie.",
    interestIds: ["law_social", "health"],
    cohortLabel: "Cohorte automne 2026",
    sourceUrl: "https://www.ulaval.ca/etudes/programmes/baccalaureat-en-psychologie",
    lastVerifiedAt: "2026-08-24",
    cutoffHistory: [
      { year: 2024, cutoff: 27.500, figureType: "last_admitted", sourceTier: "university_official" },
    ],
    prerequisites: [],
  },
  {
    id: "uqam-psychoeducation",
    name: "Baccalauréat en psychoéducation",
    institution: "Université du Québec à Montréal (UQAM)",
    description: "Intervention auprès de personnes en difficulté d'adaptation psychosociale (enfants, adolescents, familles).",
    interestIds: ["law_social", "education"],
    cohortLabel: "Cohorte automne 2026",
    placementRate: { value: 98, note: "Milieu scolaire, CISSS/CIUSSS et centres de jeunesse." },
    professionalOrders: { codes: ["OPPQ"], note: "Ordre des psychoéducateurs et psychoéducatrices du Québec." },
    sourceUrl: "https://etudier.uqam.ca/programme/baccalaureat-psychoeducation",
    lastVerifiedAt: "2026-08-24",
    cutoffHistory: [
      { year: 2024, cutoff: 25.500, figureType: "last_admitted", sourceTier: "university_official" },
    ],
    prerequisites: [],
  },
  {
    id: "ulaval-education-primaire",
    name: "Enseignement au préscolaire et au primaire",
    institution: "Université Laval",
    description: "Formation pédagogique de 4 ans avec 700+ heures de stages en milieu scolaire menant au brevet d'enseignement du Québec.",
    interestIds: ["education"],
    cohortLabel: "Cohorte automne 2026",
    placementRate: { value: 99, note: "Pénurie d'enseignants : embauche immédiate dans les centres de services scolaires." },
    professionalOrders: { codes: ["Brevet MEQ"], note: "Autorisation d'enseigner délivrée par le ministère de l'Éducation." },
    sourceUrl: "https://www.ulaval.ca/etudes/programmes/baccalaureat-en-enseignement-au-prescolaire-et-au-primaire",
    lastVerifiedAt: "2026-08-24",
    cutoffHistory: [
      { year: 2024, cutoff: 24.000, figureType: "minimum_required", sourceTier: "university_official" },
    ],
    prerequisites: [],
  },
];

export type Bursary = BursaryCriteria & {
  name: string;
  sourceOrg: string;
  amountMin: number | null;
  deadlinePrecision?: "day" | "month";
  applicationUrl: string | null;
  hasPublicApplicationLink: boolean;
  requiresEssay: boolean;
  requiresRecommendation: boolean;
  sourceUrl: string;
  lastVerifiedAt: string;
};

export const BURSARIES: Bursary[] = [
  // --- PROGRAMMES PROVINCIAUX ET GOUVERNEMENTAUX ---
  {
    id: "bourse-perspective-quebec",
    name: "Bourses Perspective Québec (TI, Génie, Santé, Éducation)",
    sourceOrg: "Gouvernement du Québec (MES)",
    cegepId: null,
    eligibleCegepPrograms: null,
    eligibleUniversityPrograms: null,
    minRScore: null,
    minSession: 1,
    tagCriteria: ["research", "community_engagement"],
    amountMin: 2500,
    amountMax: 20000,
    deadlineIso: "2027-02-28",
    applicationUrl: "https://www.quebec.ca/education/aide-financiere-aux-etudes/bourses-perspective-quebec",
    hasPublicApplicationLink: true,
    requiresEssay: false,
    requiresRecommendation: false,
    sourceUrl: "https://www.quebec.ca/education/aide-financiere-aux-etudes/bourses-perspective-quebec",
    lastVerifiedAt: "2026-08-24",
  },
  {
    id: "afe-prets-bourses",
    name: "Programme de prêts et bourses (AFE)",
    sourceOrg: "Aide financière aux études — Gouvernement du Québec",
    cegepId: null,
    eligibleCegepPrograms: null,
    eligibleUniversityPrograms: null,
    minRScore: null,
    minSession: null,
    tagCriteria: null,
    amountMin: 1000,
    amountMax: 15000,
    deadlineIso: null,
    applicationUrl: "https://www.quebec.ca/education/aide-financiere-aux-etudes",
    hasPublicApplicationLink: true,
    requiresEssay: false,
    requiresRecommendation: false,
    sourceUrl: "https://www.quebec.ca/education/aide-financiere-aux-etudes",
    lastVerifiedAt: "2026-08-24",
  },
  {
    id: "bourses-mes-excellence-collegiale",
    name: "Bourse d'excellence pour la persévérance et la réussite collégiale",
    sourceOrg: "Ministère de l'Enseignement supérieur",
    cegepId: null,
    eligibleCegepPrograms: null,
    eligibleUniversityPrograms: null,
    minRScore: 28.0,
    minSession: 2,
    tagCriteria: ["perseverance", "leadership"],
    amountMin: 1000,
    amountMax: 2500,
    deadlineIso: "2026-11-30",
    applicationUrl: null,
    hasPublicApplicationLink: false,
    requiresEssay: false,
    requiresRecommendation: true,
    sourceUrl: "https://www.quebec.ca/education/etudier-au-quebec/aide-financiere",
    lastVerifiedAt: "2026-08-24",
  },

  // --- GRANDES FONDATIONS NATIONALES & CORPORATIVES ---
  {
    id: "desjardins-bourses-etudes",
    name: "Bourse d'études de la Fondation Desjardins (Collégial & Universitaire)",
    sourceOrg: "Fondation Desjardins",
    cegepId: null,
    eligibleCegepPrograms: null,
    eligibleUniversityPrograms: null,
    minRScore: null,
    minSession: null,
    tagCriteria: ["volunteering", "community_engagement", "perseverance"],
    amountMin: 1000,
    amountMax: 5000,
    deadlineIso: "2027-03-31",
    applicationUrl: "https://www.desjardins.com/a-propos/engagements/fondation-desjardins/bourses-etudes/",
    hasPublicApplicationLink: true,
    requiresEssay: true,
    requiresRecommendation: false,
    sourceUrl: "https://www.desjardins.com/a-propos/engagements/fondation-desjardins/bourses-etudes/",
    lastVerifiedAt: "2026-08-24",
  },
  {
    id: "loran-scholars-award",
    name: "Bourse Loran de premier cycle",
    sourceOrg: "Fondation Bourses Loran",
    cegepId: null,
    eligibleCegepPrograms: null,
    eligibleUniversityPrograms: null,
    minRScore: 29.0,
    minSession: 3,
    tagCriteria: ["leadership", "volunteering", "community_engagement"],
    amountMin: 10000,
    amountMax: 100000,
    deadlineIso: "2026-10-15",
    applicationUrl: "https://loranscholar.ca/fr/",
    hasPublicApplicationLink: true,
    requiresEssay: true,
    requiresRecommendation: true,
    sourceUrl: "https://loranscholar.ca/fr/",
    lastVerifiedAt: "2026-08-24",
  },
  {
    id: "schulich-leader-scholarship",
    name: "Bourse Schulich Leader (STIM / Sciences, Technologie, Ingénierie, Maths)",
    sourceOrg: "Schulich Foundation",
    cegepId: null,
    eligibleCegepPrograms: ["200.B0", "200.B1", "420.B0"],
    eligibleUniversityPrograms: ["poly-genie-logiciel", "ulaval-genie-logiciel", "mcgill-computer-science"],
    minRScore: 32.0,
    minSession: 3,
    tagCriteria: ["research", "leadership"],
    amountMin: 100000,
    amountMax: 120000,
    deadlineIso: "2027-01-31",
    applicationUrl: "https://schulichleaders.com/fr/",
    hasPublicApplicationLink: true,
    requiresEssay: true,
    requiresRecommendation: true,
    sourceUrl: "https://schulichleaders.com/fr/",
    lastVerifiedAt: "2026-08-24",
  },
  {
    id: "hydro-quebec-collegial",
    name: "Bourses d'excellence Hydro-Québec pour les étudiants en sciences et génie",
    sourceOrg: "Fondation Hydro-Québec",
    cegepId: null,
    eligibleCegepPrograms: ["200.B0", "200.B1", "243.B0", "420.B0"],
    eligibleUniversityPrograms: null,
    minRScore: 28.5,
    minSession: 2,
    tagCriteria: ["research", "environment"],
    amountMin: 2000,
    amountMax: 3000,
    deadlineIso: "2026-11-15",
    applicationUrl: "https://www.hydroquebec.com/engagements/bourses-etudes/",
    hasPublicApplicationLink: true,
    requiresEssay: true,
    requiresRecommendation: false,
    sourceUrl: "https://www.hydroquebec.com/engagements/bourses-etudes/",
    lastVerifiedAt: "2026-08-24",
  },
  {
    id: "forces-avenir-collegial",
    name: "Prix et Bourses Forces AVENIR Collégial (Projets engagés & Personnalités)",
    sourceOrg: "Forces AVENIR",
    cegepId: null,
    eligibleCegepPrograms: null,
    eligibleUniversityPrograms: null,
    minRScore: null,
    minSession: 1,
    tagCriteria: ["leadership", "community_engagement", "volunteering"],
    amountMin: 1000,
    amountMax: 10000,
    deadlineIso: "2027-03-15",
    applicationUrl: "https://www.forcesavenir.qc.ca/collegial/",
    hasPublicApplicationLink: true,
    requiresEssay: true,
    requiresRecommendation: true,
    sourceUrl: "https://www.forcesavenir.qc.ca/collegial/",
    lastVerifiedAt: "2026-08-24",
  },
  {
    id: "aleo-faeq-sport-etudes",
    name: "Bourse Fondation Aléo (FAEQ) — Athlètes d'excellence et Sport-Études",
    sourceOrg: "Fondation Aléo",
    cegepId: null,
    eligibleCegepPrograms: null,
    eligibleUniversityPrograms: null,
    minRScore: null,
    minSession: null,
    tagCriteria: ["sports", "perseverance"],
    amountMin: 1500,
    amountMax: 4000,
    deadlineIso: "2026-10-30",
    applicationUrl: "https://fondationaleo.ca/",
    hasPublicApplicationLink: true,
    requiresEssay: false,
    requiresRecommendation: true,
    sourceUrl: "https://fondationaleo.ca/",
    lastVerifiedAt: "2026-08-24",
  },

  // --- FONDATIONS DE CÉGEPS (QUÉBEC, MONTRÉAL & RÉGIONS) ---
  {
    id: "excellence-sciences-nature-sainte-foy",
    name: "Bourse d'excellence en sciences de la nature",
    sourceOrg: "Fondation du Cégep de Sainte-Foy",
    cegepId: "sainte-foy",
    eligibleCegepPrograms: ["200.B0", "200.B1"],
    eligibleUniversityPrograms: null,
    minRScore: 27.0,
    minSession: null,
    tagCriteria: ["research"],
    amountMin: 1500,
    amountMax: 1500,
    deadlineIso: "2026-10-15",
    applicationUrl: "https://www.cegep-ste-foy.qc.ca/fondation/",
    hasPublicApplicationLink: true,
    requiresEssay: false,
    requiresRecommendation: false,
    sourceUrl: "https://www.cegep-ste-foy.qc.ca/fondation/bourses/",
    lastVerifiedAt: "2026-08-24",
  },
  {
    id: "implication-communautaire-sainte-foy",
    name: "Bourse d'implication communautaire Desjardins",
    sourceOrg: "Fondation du Cégep de Sainte-Foy",
    cegepId: "sainte-foy",
    eligibleCegepPrograms: null,
    eligibleUniversityPrograms: null,
    minRScore: null,
    minSession: null,
    tagCriteria: ["volunteering", "community_engagement"],
    amountMin: 500,
    amountMax: 1000,
    deadlineIso: "2026-11-01",
    applicationUrl: "https://www.cegep-ste-foy.qc.ca/fondation/",
    hasPublicApplicationLink: true,
    requiresEssay: true,
    requiresRecommendation: false,
    sourceUrl: "https://www.cegep-ste-foy.qc.ca/fondation/bourses/",
    lastVerifiedAt: "2026-08-24",
  },
  {
    id: "perseverance-sainte-foy",
    name: "Bourse de persévérance scolaire",
    sourceOrg: "Fondation du Cégep de Sainte-Foy",
    cegepId: "sainte-foy",
    eligibleCegepPrograms: null,
    eligibleUniversityPrograms: null,
    minRScore: null,
    minSession: 2,
    tagCriteria: ["perseverance"],
    amountMin: 500,
    amountMax: 1000,
    deadlineIso: null,
    applicationUrl: null,
    hasPublicApplicationLink: false,
    requiresEssay: false,
    requiresRecommendation: true,
    sourceUrl: "https://www.cegep-ste-foy.qc.ca/fondation/bourses/",
    lastVerifiedAt: "2026-08-24",
  },
  {
    id: "garneau-excellence-scolaire",
    name: "Bourse d'excellence académique de la Fondation Garneau",
    sourceOrg: "Fondation Cégep Garneau",
    cegepId: "garneau",
    eligibleCegepPrograms: null,
    eligibleUniversityPrograms: null,
    minRScore: 28.0,
    minSession: 2,
    tagCriteria: ["leadership"],
    amountMin: 1000,
    amountMax: 1500,
    deadlineIso: "2026-10-25",
    applicationUrl: "https://www.cegepgarneau.ca/fondation/bourses",
    hasPublicApplicationLink: true,
    requiresEssay: false,
    requiresRecommendation: false,
    sourceUrl: "https://www.cegepgarneau.ca/fondation/bourses",
    lastVerifiedAt: "2026-08-24",
  },
  {
    id: "garneau-engagement-etudiant",
    name: "Bourse d'engagement socioculturel et sportif",
    sourceOrg: "Fondation Cégep Garneau",
    cegepId: "garneau",
    eligibleCegepPrograms: null,
    eligibleUniversityPrograms: null,
    minRScore: null,
    minSession: 1,
    tagCriteria: ["volunteering", "sports", "arts_culture"],
    amountMin: 500,
    amountMax: 1000,
    deadlineIso: "2026-11-10",
    applicationUrl: "https://www.cegepgarneau.ca/fondation/bourses",
    hasPublicApplicationLink: true,
    requiresEssay: true,
    requiresRecommendation: false,
    sourceUrl: "https://www.cegepgarneau.ca/fondation/bourses",
    lastVerifiedAt: "2026-08-24",
  },
  {
    id: "limoilou-merite-etudiant",
    name: "Bourse de mérite et réussite de la Fondation Limoilou",
    sourceOrg: "Fondation Québec Philanthrope — Fonds Cégep Limoilou",
    cegepId: "limoilou",
    eligibleCegepPrograms: null,
    eligibleUniversityPrograms: null,
    minRScore: 27.5,
    minSession: 2,
    tagCriteria: ["perseverance"],
    amountMin: 750,
    amountMax: 1500,
    deadlineIso: "2026-10-31",
    applicationUrl: "https://www.cegeplimoilou.ca/etudiants/bourses/",
    hasPublicApplicationLink: true,
    requiresEssay: false,
    requiresRecommendation: true,
    sourceUrl: "https://www.cegeplimoilou.ca/etudiants/bourses/",
    lastVerifiedAt: "2026-08-24",
  },
  {
    id: "maisonneuve-bourses-reussite",
    name: "Bourse d'excellence et persévérance de la Fondation Maisonneuve",
    sourceOrg: "Fondation du Cégep de Maisonneuve",
    cegepId: "maisonneuve",
    eligibleCegepPrograms: null,
    eligibleUniversityPrograms: null,
    minRScore: 26.5,
    minSession: 2,
    tagCriteria: ["perseverance", "volunteering"],
    amountMin: 500,
    amountMax: 1500,
    deadlineIso: "2026-11-15",
    applicationUrl: "https://www.cmaisonneuve.qc.ca/fondation/bourses/",
    hasPublicApplicationLink: true,
    requiresEssay: true,
    requiresRecommendation: false,
    sourceUrl: "https://www.cmaisonneuve.qc.ca/fondation/bourses/",
    lastVerifiedAt: "2026-08-24",
  },
  {
    id: "vieux-montreal-bourses-arts-sciences",
    name: "Bourse de la Fondation du Cégep du Vieux Montréal",
    sourceOrg: "Fondation du Cégep du Vieux Montréal",
    cegepId: "vieux-montreal",
    eligibleCegepPrograms: null,
    eligibleUniversityPrograms: null,
    minRScore: null,
    minSession: 1,
    tagCriteria: ["arts_culture", "community_engagement"],
    amountMin: 500,
    amountMax: 1200,
    deadlineIso: "2026-11-20",
    applicationUrl: "https://www.cvm.qc.ca/fondation/bourses/",
    hasPublicApplicationLink: true,
    requiresEssay: true,
    requiresRecommendation: false,
    sourceUrl: "https://www.cvm.qc.ca/fondation/bourses/",
    lastVerifiedAt: "2026-08-24",
  },
  {
    id: "ahuntsic-bourses-fondation",
    name: "Bourses d'encouragement aux études du Collège Ahuntsic",
    sourceOrg: "Fondation Collège Ahuntsic",
    cegepId: "ahuntsic",
    eligibleCegepPrograms: null,
    eligibleUniversityPrograms: null,
    minRScore: null,
    minSession: 1,
    tagCriteria: ["perseverance", "community_engagement"],
    amountMin: 500,
    amountMax: 1000,
    deadlineIso: "2026-11-05",
    applicationUrl: "https://www.collegeahuntsic.qc.ca/fondation/bourses",
    hasPublicApplicationLink: true,
    requiresEssay: false,
    requiresRecommendation: true,
    sourceUrl: "https://www.collegeahuntsic.qc.ca/fondation/bourses",
    lastVerifiedAt: "2026-08-24",
  },
  {
    id: "dawson-foundation-bursary",
    name: "Dawson College Foundation Academic & Leadership Award",
    sourceOrg: "Dawson College Foundation",
    cegepId: "dawson",
    eligibleCegepPrograms: null,
    eligibleUniversityPrograms: null,
    minRScore: 28.0,
    minSession: 2,
    tagCriteria: ["leadership", "volunteering"],
    amountMin: 1000,
    amountMax: 2000,
    deadlineIso: "2026-10-30",
    applicationUrl: "https://www.dawsoncollege.qc.ca/awards-scholarships/",
    hasPublicApplicationLink: true,
    requiresEssay: true,
    requiresRecommendation: true,
    sourceUrl: "https://www.dawsoncollege.qc.ca/awards-scholarships/",
    lastVerifiedAt: "2026-08-24",
  },
  {
    id: "sherbrooke-cegep-bourses",
    name: "Bourse d'excellence et engagement de la Fondation Cégep de Sherbrooke",
    sourceOrg: "Fondation Cégep de Sherbrooke",
    cegepId: "sherbrooke",
    eligibleCegepPrograms: null,
    eligibleUniversityPrograms: null,
    minRScore: 27.0,
    minSession: 2,
    tagCriteria: ["volunteering", "sports", "arts_culture"],
    amountMin: 500,
    amountMax: 1500,
    deadlineIso: "2026-11-15",
    applicationUrl: "https://cegepsherbrooke.qc.ca/fr/fondation/bourses",
    hasPublicApplicationLink: true,
    requiresEssay: true,
    requiresRecommendation: false,
    sourceUrl: "https://cegepsherbrooke.qc.ca/fr/fondation/bourses",
    lastVerifiedAt: "2026-08-24",
  },
  {
    id: "trois-rivieres-fondation-bourses",
    name: "Bourses d'études de la Fondation du Cégep de Trois-Rivières",
    sourceOrg: "Fondation du Cégep de Trois-Rivières",
    cegepId: "trois-rivieres",
    eligibleCegepPrograms: null,
    eligibleUniversityPrograms: null,
    minRScore: null,
    minSession: 1,
    tagCriteria: ["perseverance", "leadership"],
    amountMin: 500,
    amountMax: 1000,
    deadlineIso: "2026-11-10",
    applicationUrl: "https://fondationcegeptr.qc.ca/bourses/",
    hasPublicApplicationLink: true,
    requiresEssay: false,
    requiresRecommendation: true,
    sourceUrl: "https://fondationcegeptr.qc.ca/bourses/",
    lastVerifiedAt: "2026-08-24",
  },
  {
    id: "outaouais-fondation-bourses",
    name: "Bourse de persévérance et leadership de la Fondation du Cégep de l'Outaouais",
    sourceOrg: "Fondation du Cégep de l'Outaouais",
    cegepId: "outaouais",
    eligibleCegepPrograms: null,
    eligibleUniversityPrograms: null,
    minRScore: null,
    minSession: 2,
    tagCriteria: ["leadership", "perseverance"],
    amountMin: 500,
    amountMax: 1000,
    deadlineIso: "2026-11-20",
    applicationUrl: "https://cegepoutaouais.qc.ca/fondation/bourses/",
    hasPublicApplicationLink: true,
    requiresEssay: true,
    requiresRecommendation: false,
    sourceUrl: "https://cegepoutaouais.qc.ca/fondation/bourses/",
    lastVerifiedAt: "2026-08-24",
  },
  {
    id: "chicoutimi-fondation-bourses",
    name: "Bourse de réussite et engagement de la Fondation du Cégep de Chicoutimi",
    sourceOrg: "Fondation du Cégep de Chicoutimi",
    cegepId: "chicoutimi",
    eligibleCegepPrograms: null,
    eligibleUniversityPrograms: null,
    minRScore: 26.5,
    minSession: 1,
    tagCriteria: ["community_engagement", "research"],
    amountMin: 500,
    amountMax: 1200,
    deadlineIso: "2026-11-15",
    applicationUrl: "https://cchic.ca/fondation/bourses/",
    hasPublicApplicationLink: true,
    requiresEssay: false,
    requiresRecommendation: false,
    sourceUrl: "https://cchic.ca/fondation/bourses/",
    lastVerifiedAt: "2026-08-24",
  },
  {
    id: "rimouski-fondation-bourses",
    name: "Bourses d'études et d'implication de la Fondation du Cégep de Rimouski",
    sourceOrg: "Fondation du Cégep de Rimouski",
    cegepId: "rimouski",
    eligibleCegepPrograms: null,
    eligibleUniversityPrograms: null,
    minRScore: null,
    minSession: 1,
    tagCriteria: ["environment", "volunteering"],
    amountMin: 500,
    amountMax: 1000,
    deadlineIso: "2026-11-10",
    applicationUrl: "https://www.cegep-rimouski.qc.ca/fondation",
    hasPublicApplicationLink: true,
    requiresEssay: true,
    requiresRecommendation: false,
    sourceUrl: "https://www.cegep-rimouski.qc.ca/fondation",
    lastVerifiedAt: "2026-08-24",
  },
];

export type Deadline = {
  id: string;
  titleFr: string;
  titleEn: string;
  dateIso: string;
  detailFr: string;
  detailEn: string;
  urgent?: boolean;
  sourceUrl: string;
  lastVerifiedAt: string;
};

export const DEADLINES: Deadline[] = ALL_IMPORTANT_DATES.map((d) => ({
  id: d.id,
  titleFr: d.titleFr,
  titleEn: d.titleEn,
  dateIso: d.dateIso,
  detailFr: d.detailFr,
  detailEn: d.detailEn,
  sourceUrl: d.sourceUrl,
  lastVerifiedAt: d.lastVerifiedAt,
}));

export const STUDENT_SAMPLE = {
  cegep: CEGEPS[0],
  program: CEGEP_PROGRAMS[0],
  session: SESSIONS[0],
  rScoreEstimated: 32.4,
};

export const DASHBOARD_SAMPLE = {
  currentEstimate: 32.41,
  currentSessionLabelFr: "Automne 2026",
  currentSessionLabelEn: "Fall 2026",
  confirmedSessions: [
    { sessionFr: "Hiver 2026", sessionEn: "Winter 2026", score: 31.85 },
    { sessionFr: "Automne 2025", sessionEn: "Fall 2025", score: 30.2 },
  ],
  currentCourses: [
    {
      nameFr: "Calcul différentiel",
      nameEn: "Calculus I",
      code: "201-NYA-05",
      grade: 88,
      groupAverage: 72,
    },
    {
      nameFr: "Physique — Mécanique",
      nameEn: "Physics: Mechanics",
      code: "203-NYA-05",
      grade: 82,
      groupAverage: 75,
    },
    {
      nameFr: "Philosophie et rationalité",
      nameEn: "Philosophy",
      code: "340-101-MQ",
      grade: 76,
      groupAverage: 78,
    },
  ],
  goalProgram: {
    nameFr: "Droit (UdeM)",
    nameEn: "Law (UdeM)",
    cutoffHistory: [
      { year: 2024, cutoff: 31.505, figureType: "last_admitted" as const, sourceTier: "university_official" as const },
      { year: 2024, cutoff: 33.168, figureType: "average" as const, sourceTier: "university_official" as const },
      { year: 2024, cutoff: 38.058, figureType: "maximum" as const, sourceTier: "university_official" as const },
    ],
    sourceUrl: "https://admission.umontreal.ca/statistiques-dadmission-cote-r/",
    lastVerifiedAt: "2026-08-24",
  },
};
