-- GENERATED by scripts/db/build-full-schema.ts from supabase/migrations/*.sql.
-- Do not edit by hand: add a migration and run `npm run build:schema`.
-- 12 migrations.

-- >>> migrations/20260824194654_institutions.sql
-- Cluster 1: institutions. See docs/01-data-architecture.md.
-- Rarely changes; no RLS needed beyond the public-read policy every catalog
-- cluster gets (see cegep_catalog migration for the rationale).

create extension if not exists pgcrypto;

create table cegeps (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  short_code text unique not null,        -- 'sainte-foy', 'limoilou', 'garneau', 'champlain-slc'
  sector text not null check (sector in ('public_french','public_english','private')),
  region text not null default 'Quebec City',
  website_url text,
  admission_service text,                  -- 'SRACQ', 'direct', etc.
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table universities (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  short_code text unique not null,
  website_url text,
  bci_member boolean default true
);

alter table cegeps enable row level security;
create policy "public read" on cegeps for select using (true);

alter table universities enable row level security;
create policy "public read" on universities for select using (true);

-- >>> migrations/20260824194656_cegep_catalog.sql
-- Cluster 2: cegep-side catalog. See docs/01-data-architecture.md.
--
-- RLS note (addition beyond the doc's literal SQL, flagged in the build plan):
-- the spec writes no RLS for clusters 1-5, but these tables are meant to be
-- publicly browsable (program directory) while writes should only ever happen
-- via the service-role key from scripts/collectors/, which bypasses RLS. A
-- single public read-only policy accomplishes that on every table below.

create table cegep_programs (
  id uuid primary key default gen_random_uuid(),
  cegep_id uuid references cegeps(id) not null,
  program_code text,                       -- ministerial code, e.g. '200.B0'
  name text not null,
  type text check (type in ('pre_university','technical')) not null,
  created_at timestamptz default now()
);

create table courses (
  id uuid primary key default gen_random_uuid(),
  course_code text unique not null,        -- e.g. '201-NYA-05'
  discipline_code text,                    -- '201' = mathematics, etc.
  name text not null,
  name_en text,
  weighting numeric,                       -- 'ponderation'
  created_at timestamptz default now()
);

alter table cegep_programs enable row level security;
create policy "public read" on cegep_programs for select using (true);

alter table courses enable row level security;
create policy "public read" on courses for select using (true);

-- >>> migrations/20260824194657_university_targets.sql
-- Cluster 3: university-side targets. See docs/01-data-architecture.md.

create table university_programs (
  id uuid primary key default gen_random_uuid(),
  university_id uuid references universities(id) not null,
  name text not null,
  degree_type text,                        -- 'BAA', 'BSc', 'MD', etc.
  -- No overall_cutoff column: universities publish multi-year ranges, or min/max/average,
  -- or nothing at all — never one current-year number. See the 2026-08-24 data audit and
  -- docs/01-data-architecture.md. cutoff_history is the only home for figures.
  admission_type text check (admission_type in
    ('r_score_only','r_score_plus_interview','r_score_plus_portfolio','r_score_plus_test','other')) not null,
  source_url text not null,
  last_verified_at date not null,
  created_at timestamptz default now()
);

create table university_program_prerequisites (
  id uuid primary key default gen_random_uuid(),
  university_program_id uuid references university_programs(id) not null,
  course_id uuid references courses(id) not null,
  required boolean default true,
  unique(university_program_id, course_id)
);

create table university_program_grade_floors (
  id uuid primary key default gen_random_uuid(),
  university_program_id uuid references university_programs(id) not null,
  course_id uuid references courses(id) not null,
  min_grade numeric not null,              -- e.g. HEC's 26.5 math floor
  floor_type text check (floor_type in ('course_cote_r_floor','course_percentage_floor')) not null,
  source_url text not null,
  notes text
);

-- Every published figure carries its own year AND its own figure type: universities
-- publish last-admitted, minimum-required, maximum, average, or a range_low/range_high pair
-- for the SAME program and year, never one canonical number. A student's score is compared
-- against the resulting low/high band (see src/lib/rscore/cutoff-range.ts), never against a
-- single cutoff.
create table cutoff_history (
  id uuid primary key default gen_random_uuid(),
  university_program_id uuid references university_programs(id) not null,
  admission_year int not null,
  cutoff numeric not null,
  figure_type text check (figure_type in
    ('last_admitted','minimum_required','maximum','average','range_low','range_high')) not null,
  -- university_official always wins over cegep_compiled when both exist for a program+year.
  source_tier text check (source_tier in ('university_official','cegep_compiled')) not null,
  source_url text not null,
  source_type text check (source_type in ('official_pdf','cegep_published','bci','other')) not null,
  verified_at date not null,
  unique(university_program_id, admission_year, figure_type)
);

alter table university_programs enable row level security;
create policy "public read" on university_programs for select using (true);

alter table university_program_prerequisites enable row level security;
create policy "public read" on university_program_prerequisites for select using (true);

alter table university_program_grade_floors enable row level security;
create policy "public read" on university_program_grade_floors for select using (true);

alter table cutoff_history enable row level security;
create policy "public read" on cutoff_history for select using (true);

-- >>> migrations/20260824194659_bursaries.sql
-- Cluster 4: bursaries. See docs/01-data-architecture.md and
-- docs/03-bursary-matching-system.md for the matching logic that reads this
-- table. Eligibility fields here are intentionally non-sensitive only -- no
-- income, no household data.

create table bursaries (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  source_org text not null,                -- 'Fondation du Cegep de Sainte-Foy', 'AFE', etc.
  cegep_id uuid references cegeps(id),     -- null = province-wide / not cegep-specific
  category text check (category in
    ('financial_need','academic_merit','athletics','arts_culture',
     'community_engagement','perseverance','program_specific','mobility','event_based','other')) not null,
  amount_min numeric,
  amount_max numeric,
  deadline_type text check (deadline_type in ('fixed_date','recurring_annual','rolling')) not null,
  deadline_date date,
  application_url text not null,
  description text,
  -- Non-sensitive eligibility criteria only. No income, no household data. See 03-bursary-matching-system.md.
  eligible_cegep_programs uuid[],          -- null = open to any program at the cegep
  eligible_university_programs uuid[],     -- for program-specific bursaries tied to a target field of study
  min_r_score numeric,
  min_session int,
  requires_essay boolean default false,
  requires_recommendation boolean default false,
  tag_criteria text[],                     -- matched against student_profiles.self_tags
  last_verified_at date not null,
  created_at timestamptz default now()
);

alter table bursaries enable row level security;
create policy "public read" on bursaries for select using (true);

-- >>> migrations/20260824194701_deadlines.sql
-- Cluster 5: deadlines (admission rounds, AFE, withdrawal dates; bursary
-- deadlines live on the bursaries row itself and get unioned in at query
-- time, not duplicated here). See docs/01-data-architecture.md.

create table deadlines (
  id uuid primary key default gen_random_uuid(),
  type text check (type in ('sracq_round','sram_round','afe_deadline','withdrawal_no_penalty','other')) not null,
  title text not null,
  date date not null,
  applies_to_cegep_id uuid references cegeps(id),  -- null = province-wide
  source_url text not null,
  last_verified_at date not null
);

alter table deadlines enable row level security;
create policy "public read" on deadlines for select using (true);

-- >>> migrations/20260824194703_student_data.sql
-- Cluster 6: student data (RLS-protected; each table locked to auth.uid()).
-- See docs/01-data-architecture.md. Policies copied verbatim from the spec.

create table student_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  cegep_id uuid references cegeps(id),
  cegep_program_id uuid references cegep_programs(id),
  current_session int,
  self_tags text[] default '{}',           -- e.g. 'sports','arts','community_engagement','leadership'
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
alter table student_profiles enable row level security;
create policy "own profile only" on student_profiles
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create table student_course_grades (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade not null,
  session int not null,
  course_id uuid references courses(id),
  course_name_freetext text,               -- fallback when the course isn't in the catalog yet
  grade numeric,
  cote_z numeric,                          -- optional, if the student's own portal shows it
  created_at timestamptz default now()
);
alter table student_course_grades enable row level security;
create policy "own grades only" on student_course_grades
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create table student_r_score_confirmations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade not null,
  session int not null,
  official_cote_r numeric not null,        -- self-reported from the student's own cegep portal
  confirmed_at timestamptz default now(),
  unique(user_id, session)
);
alter table student_r_score_confirmations enable row level security;
create policy "own confirmations only" on student_r_score_confirmations
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create table student_targets (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade not null,
  university_program_id uuid references university_programs(id) not null,
  notes text,
  created_at timestamptz default now()
);
alter table student_targets enable row level security;
create policy "own targets only" on student_targets
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- >>> migrations/20260824194704_staging_tables.sql
-- Cluster 7: staging tables (this repo's own design, cross-checked against
-- docs/02-scraping-collection-plan.md's pipeline architecture -- not defined
-- by name in docs/01-data-architecture.md, which only names the production
-- schema). One per scraped/compiled production table in clusters 2-5 (not 1
-- or 6: institutions rarely change, student data isn't scraped), matching
-- the naming docs/02-scraping-collection-plan.md itself uses
-- ("staging_university_programs", "staging_bursaries").
--
-- Each carries the same business columns as its production counterpart,
-- relaxed: FK-shaped columns are plain nullable uuid with no enforced
-- reference (staging data is inherently unvalidated -- a scraped row may
-- point at an entity that doesn't exist in production yet), and unique
-- constraints are dropped. Every table also carries shared pipeline
-- metadata: where the raw snapshot lives, who/when collected it, the diff
-- against the last promoted version, and its human review status.
--
-- RLS is enabled with zero policies for anon/authenticated (default-deny).
-- Only the service-role key (scripts/collectors/lib/staging-client.ts)
-- reads or writes these tables, and that key bypasses RLS entirely.

create table staging_cegep_programs (
  id uuid primary key default gen_random_uuid(),
  cegep_id uuid,
  program_code text,
  name text not null,
  type text check (type in ('pre_university','technical')) not null,
  created_at timestamptz,
  raw_snapshot_path text,
  collected_at timestamptz not null default now(),
  collector_name text not null,
  diff_summary jsonb,
  review_status text check (review_status in ('pending','flagged','approved','rejected')) not null default 'pending',
  promoted_at timestamptz,
  promoted_by text
);

create table staging_courses (
  id uuid primary key default gen_random_uuid(),
  course_code text not null,
  discipline_code text,
  name text not null,
  name_en text,
  weighting numeric,
  created_at timestamptz,
  raw_snapshot_path text,
  collected_at timestamptz not null default now(),
  collector_name text not null,
  diff_summary jsonb,
  review_status text check (review_status in ('pending','flagged','approved','rejected')) not null default 'pending',
  promoted_at timestamptz,
  promoted_by text
);

create table staging_university_programs (
  id uuid primary key default gen_random_uuid(),
  university_id uuid,
  name text not null,
  degree_type text,
  -- No overall_cutoff: see the matching note on the production university_programs table.
  admission_type text check (admission_type in
    ('r_score_only','r_score_plus_interview','r_score_plus_portfolio','r_score_plus_test','other')) not null,
  source_url text not null,
  last_verified_at date not null,
  created_at timestamptz,
  raw_snapshot_path text,
  collected_at timestamptz not null default now(),
  collector_name text not null,
  diff_summary jsonb,
  review_status text check (review_status in ('pending','flagged','approved','rejected')) not null default 'pending',
  promoted_at timestamptz,
  promoted_by text
);

create table staging_university_program_prerequisites (
  id uuid primary key default gen_random_uuid(),
  university_program_id uuid,
  course_id uuid,
  required boolean,
  raw_snapshot_path text,
  collected_at timestamptz not null default now(),
  collector_name text not null,
  diff_summary jsonb,
  review_status text check (review_status in ('pending','flagged','approved','rejected')) not null default 'pending',
  promoted_at timestamptz,
  promoted_by text
);

create table staging_university_program_grade_floors (
  id uuid primary key default gen_random_uuid(),
  university_program_id uuid,
  course_id uuid,
  min_grade numeric not null,
  floor_type text check (floor_type in ('course_cote_r_floor','course_percentage_floor')) not null,
  source_url text not null,
  notes text,
  raw_snapshot_path text,
  collected_at timestamptz not null default now(),
  collector_name text not null,
  diff_summary jsonb,
  review_status text check (review_status in ('pending','flagged','approved','rejected')) not null default 'pending',
  promoted_at timestamptz,
  promoted_by text
);

create table staging_cutoff_history (
  id uuid primary key default gen_random_uuid(),
  university_program_id uuid,
  admission_year int not null,
  cutoff numeric not null,
  figure_type text check (figure_type in
    ('last_admitted','minimum_required','maximum','average','range_low','range_high')) not null,
  source_tier text check (source_tier in ('university_official','cegep_compiled')) not null,
  source_url text not null,
  source_type text check (source_type in ('official_pdf','cegep_published','bci','other')) not null,
  verified_at date not null,
  raw_snapshot_path text,
  collected_at timestamptz not null default now(),
  collector_name text not null,
  diff_summary jsonb,
  review_status text check (review_status in ('pending','flagged','approved','rejected')) not null default 'pending',
  promoted_at timestamptz,
  promoted_by text
);

create table staging_bursaries (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  source_org text not null,
  cegep_id uuid,
  category text check (category in
    ('financial_need','academic_merit','athletics','arts_culture',
     'community_engagement','perseverance','program_specific','mobility','event_based','other')) not null,
  amount_min numeric,
  amount_max numeric,
  deadline_type text check (deadline_type in ('fixed_date','recurring_annual','rolling')) not null,
  deadline_date date,
  application_url text not null,
  description text,
  eligible_cegep_programs uuid[],
  eligible_university_programs uuid[],
  min_r_score numeric,
  min_session int,
  requires_essay boolean default false,
  requires_recommendation boolean default false,
  tag_criteria text[],
  last_verified_at date not null,
  created_at timestamptz,
  raw_snapshot_path text,
  collected_at timestamptz not null default now(),
  collector_name text not null,
  diff_summary jsonb,
  review_status text check (review_status in ('pending','flagged','approved','rejected')) not null default 'pending',
  promoted_at timestamptz,
  promoted_by text
);

create table staging_deadlines (
  id uuid primary key default gen_random_uuid(),
  type text check (type in ('sracq_round','sram_round','afe_deadline','withdrawal_no_penalty','other')) not null,
  title text not null,
  date date not null,
  applies_to_cegep_id uuid,
  source_url text not null,
  last_verified_at date not null,
  raw_snapshot_path text,
  collected_at timestamptz not null default now(),
  collector_name text not null,
  diff_summary jsonb,
  review_status text check (review_status in ('pending','flagged','approved','rejected')) not null default 'pending',
  promoted_at timestamptz,
  promoted_by text
);

alter table staging_cegep_programs enable row level security;
alter table staging_courses enable row level security;
alter table staging_university_programs enable row level security;
alter table staging_university_program_prerequisites enable row level security;
alter table staging_university_program_grade_floors enable row level security;
alter table staging_cutoff_history enable row level security;
alter table staging_bursaries enable row level security;
alter table staging_deadlines enable row level security;

-- >>> migrations/20260824200000_performance_indexes_and_rls.sql
-- Migration: 20260824200000_performance_indexes_and_rls.sql
-- Workstream 2: Database Performance, Covering Indexes, and RLS Optimization
--
-- 1. Enable pg_stat_statements for slow query profiling
-- 2. Optimize RLS policies using subquery caching: (select auth.uid()) = user_id
-- 3. Add B-Tree & composite indexes for foreign keys, join paths, and RLS predicates
-- 4. Add covering + GIN indexes for bursary matching queries
-- 5. Add review_status indexes for staging tables

-- Enable pg_stat_statements extension
create extension if not exists pg_stat_statements;

-- ============================================================================
-- 1. RLS POLICY OPTIMIZATIONS (Subquery caching avoids per-row function calls)
-- ============================================================================

-- student_profiles
drop policy if exists "own profile only" on student_profiles;
create policy "own profile only" on student_profiles
  for all using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

-- student_course_grades
drop policy if exists "own grades only" on student_course_grades;
create policy "own grades only" on student_course_grades
  for all using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

-- student_r_score_confirmations
drop policy if exists "own confirmations only" on student_r_score_confirmations;
create policy "own confirmations only" on student_r_score_confirmations
  for all using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

-- student_targets
drop policy if exists "own targets only" on student_targets;
create policy "own targets only" on student_targets
  for all using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

-- ============================================================================
-- 2. INDEXES FOR RLS & STUDENT DATA TABLES
-- ============================================================================

create index if not exists idx_student_profiles_user on student_profiles(user_id);
create index if not exists idx_student_course_grades_user_session on student_course_grades(user_id, session);
create index if not exists idx_student_r_score_confirmations_user on student_r_score_confirmations(user_id, session);
create index if not exists idx_student_targets_user on student_targets(user_id);

-- ============================================================================
-- 3. COMPOSITE INDEXES FOR UNIVERSITY & CEGEP CATALOG TABLES
-- ============================================================================

create index if not exists idx_cegep_programs_cegep on cegep_programs(cegep_id, program_code);
create index if not exists idx_univ_prereqs_prog_course on university_program_prerequisites(university_program_id, course_id);
create index if not exists idx_univ_floors_prog_course on university_program_grade_floors(university_program_id, course_id);
create index if not exists idx_cutoff_history_prog_year on cutoff_history(university_program_id, admission_year desc);
create index if not exists idx_deadlines_cegep_date on deadlines(applies_to_cegep_id, date);

-- ============================================================================
-- 4. BURSARY MATCHING COVERING & GIN INDEXES
-- ============================================================================

-- Composite covering index for scalar predicates: cegep, min R-score, and session
create index if not exists idx_bursaries_matching on bursaries(cegep_id, min_r_score, min_session);

-- GIN indexes for array membership matching (programs and tag criteria)
create index if not exists idx_bursaries_eligible_programs on bursaries using gin(eligible_cegep_programs);
create index if not exists idx_bursaries_tag_criteria on bursaries using gin(tag_criteria);

-- ============================================================================
-- 5. STAGING TABLES INDEXES (Fast review and promotion scans)
-- ============================================================================

create index if not exists idx_staging_cegep_programs_status on staging_cegep_programs(review_status);
create index if not exists idx_staging_courses_status on staging_courses(review_status);
create index if not exists idx_staging_univ_programs_status on staging_university_programs(review_status);
create index if not exists idx_staging_bursaries_status on staging_bursaries(review_status);
create index if not exists idx_staging_cutoff_history_status on staging_cutoff_history(review_status);
create index if not exists idx_staging_deadlines_status on staging_deadlines(review_status);

-- >>> migrations/20260825120000_catalog_slugs_and_onboarding.sql
-- Onboarding rework: make the scraped Quebec City catalogue addressable from the client,
-- and let a student's profile survive being written before the catalogue is seeded.
--
-- Three changes, each independent:
--
--   1. `catalog_slug` on the two program tables. The generated catalogue
--      (src/lib/data/catalog.generated.ts) keys programs by a human-readable slug, not by a
--      uuid, so routes stay readable and a re-seed cannot renumber a student's saved target.
--      Unique, so supabase/seed/catalog.sql can upsert on replay.
--
--   2. `cegep_programs.type` gains 'special'. The scrape contains "Cheminement particulier"
--      entries (Tremplin DEC and friends) that are neither pre-university nor technical.
--      Dropping them would silently hide real programs from real students.
--
--   3. `student_profiles` gains natural-key columns plus a resolver trigger. Onboarding runs
--      before the catalogue is guaranteed seeded, and the uuid FKs would reject the insert.
--      The natural keys (cegep short_code + ministerial DEC code) always accept the write;
--      the trigger backfills the FKs the moment matching catalogue rows exist. Guardrail #3
--      still holds — nothing here is financial.

-- 1 ------------------------------------------------------------------------

alter table cegep_programs add column if not exists catalog_slug text;
create unique index if not exists cegep_programs_catalog_slug_key
  on cegep_programs (catalog_slug);

alter table university_programs add column if not exists catalog_slug text;
create unique index if not exists university_programs_catalog_slug_key
  on university_programs (catalog_slug);

-- 2 ------------------------------------------------------------------------

alter table cegep_programs drop constraint if exists cegep_programs_type_check;
alter table cegep_programs add constraint cegep_programs_type_check
  check (type in ('pre_university', 'technical', 'special'));

-- 3 ------------------------------------------------------------------------

alter table student_profiles add column if not exists cegep_short_code text;
-- The ministerial DEC code ('200.B0'), which is what the client keys programs by and what
-- src/lib/matching/program-eligibility.ts matches curriculum against. NOT a per-cegep slug:
-- a DEC code is province-wide, and the same code at two cegeps is the same program.
alter table student_profiles add column if not exists cegep_program_code text;

-- R-score status the student arrived with. The official, self-reported number keeps living
-- in student_r_score_confirmations; this only records which path onboarding took so the UI
-- can keep labelling an estimate as an estimate (guardrail #2).
alter table student_profiles add column if not exists r_score_status text
  check (r_score_status in ('confirmed', 'estimated'));

create or replace function resolve_student_profile_catalog_refs()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.cegep_short_code is not null and new.cegep_id is null then
    select id into new.cegep_id from cegeps where short_code = new.cegep_short_code;
  end if;

  -- Scoped to the student's own cegep: one ministerial code is offered by several of them,
  -- and the row we want is the offering at their school.
  if new.cegep_program_code is not null and new.cegep_program_id is null and new.cegep_id is not null then
    select id into new.cegep_program_id
      from cegep_programs
     where cegep_id = new.cegep_id and program_code = new.cegep_program_code
     limit 1;
  end if;

  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists student_profiles_resolve_catalog_refs on student_profiles;
create trigger student_profiles_resolve_catalog_refs
  before insert or update on student_profiles
  for each row execute function resolve_student_profile_catalog_refs();

-- Targets picked during the university-choice quiz. `student_targets.university_program_id`
-- is a uuid FK into a table that is only populated once the seed runs, so the quiz records
-- its picks by slug and the same resolve-on-write pattern applies.
alter table student_targets alter column university_program_id drop not null;
alter table student_targets add column if not exists catalog_slug text;

create or replace function resolve_student_target_catalog_ref()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.catalog_slug is not null and new.university_program_id is null then
    select id into new.university_program_id from university_programs where catalog_slug = new.catalog_slug;
  end if;
  return new;
end;
$$;

drop trigger if exists student_targets_resolve_catalog_ref on student_targets;
create trigger student_targets_resolve_catalog_ref
  before insert or update on student_targets
  for each row execute function resolve_student_target_catalog_ref();

-- A student can only hold one row per target. Not a partial index: PostgREST's upsert
-- emits ON CONFLICT with no predicate, and a partial index would make it unusable.
-- Many NULL slugs are still allowed (unique indexes treat NULLs as distinct by default).
create unique index if not exists student_targets_user_slug_key
  on student_targets (user_id, catalog_slug);

-- >>> migrations/20260825130000_fix_catalog_slug_indexes.sql
-- Fixes the unique indexes added by 20260825120000, which were created as PARTIAL indexes
-- (`where catalog_slug is not null`).
--
-- Two problems with that:
--
--   1. `ON CONFLICT (catalog_slug)` cannot infer a partial index unless the statement repeats
--      the index predicate (`ON CONFLICT (catalog_slug) WHERE catalog_slug is not null`).
--      supabase/seed/catalog.sql does not, so it failed with:
--        42P10: there is no unique or exclusion constraint matching the ON CONFLICT specification
--
--   2. More seriously, PostgREST generates `ON CONFLICT (cols) DO UPDATE` with no predicate and
--      offers no way to add one. So `student_targets`' partial index would have broken every
--      upsert from src/lib/profile/sync.ts at runtime — a failure the seed happened to surface
--      first, but which would otherwise have shown up only once a student saved a target.
--
-- The predicate bought nothing to begin with: a unique index already permits many NULLs
-- (NULLS DISTINCT is the default), so a plain unique index has exactly the intended semantics
-- — at most one row per non-null slug, unconstrained nulls.

drop index if exists cegep_programs_catalog_slug_key;
create unique index cegep_programs_catalog_slug_key
  on cegep_programs (catalog_slug);

drop index if exists university_programs_catalog_slug_key;
create unique index university_programs_catalog_slug_key
  on university_programs (catalog_slug);

drop index if exists student_targets_user_slug_key;
create unique index student_targets_user_slug_key
  on student_targets (user_id, catalog_slug);

-- >>> migrations/20260826200000_notifications_and_program_profiles.sql
-- Migration: 20260826200000_notifications_and_program_profiles.sql
-- Part A: Notification preferences and events (habit-respecting, deduped, RLS-protected)
-- Part C: Generic program profiles for standardized pre-university DEC programs (300.A0, 200.B0)

-- ============================================================================
-- 1. NOTIFICATION PREFERENCES (RLS-protected, default false for all categories)
-- ============================================================================

create table if not exists notification_preferences (
  user_id uuid primary key references auth.users(id) on delete cascade,
  deadline_reminders boolean not null default false,
  cutoff_updates boolean not null default false,
  new_bursary_matches boolean not null default false,
  grade_window_reminders boolean not null default false,
  updated_at timestamptz default now()
);

alter table notification_preferences enable row level security;

create policy "own prefs only" on notification_preferences
  for all using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

create index if not exists idx_notif_prefs_user on notification_preferences(user_id);

-- ============================================================================
-- 2. NOTIFICATION EVENTS (RLS-protected, deterministic dedupe_key)
-- ============================================================================

create table if not exists notification_events (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade not null,
  category text check (category in
    ('deadline_reminder','cutoff_update','new_bursary_match','grade_window','counselor_season')) not null,
  subject_type text not null,          -- 'bursary','university_program','deadline'
  subject_id uuid not null,
  payload jsonb,                       -- rendered copy variables, e.g. { "days_left": 9, "amount": 500 }
  scheduled_for timestamptz not null,
  sent_at timestamptz,
  dedupe_key text not null,            -- prevents re-sending the same event twice
  created_at timestamptz default now(),
  unique(user_id, dedupe_key)
);

alter table notification_events enable row level security;

create policy "own events only" on notification_events
  for all using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

create index if not exists idx_notif_events_user on notification_events(user_id);
create index if not exists idx_notif_events_scheduled on notification_events(scheduled_for, sent_at);

-- ============================================================================
-- 3. GENERIC PROGRAM PROFILES (Standardized DEC profiles across cégeps)
-- ============================================================================

create table if not exists generic_program_profiles (
  id uuid primary key default gen_random_uuid(),
  program_code text unique not null,        -- '300.A0', '200.B0'
  name text not null,
  description text not null,                -- factual, sourced, no ranking language
  profils jsonb not null default '[]',       -- [{ "name": "Individu", "description": "..." }, ...]
  typical_courses text[],
  leads_to_program_categories text[],        -- broad factual categories, not a ranked fit list
  factual_career_examples text[],            -- named, sourced examples only from program directories
  source_url text not null,
  last_verified_at date not null,
  created_at timestamptz default now()
);

alter table generic_program_profiles enable row level security;

create policy "public read" on generic_program_profiles for select using (true);

create index if not exists idx_generic_prog_profiles_code on generic_program_profiles(program_code);

-- >>> migrations/20260902120000_profile_goal_fields_catalog_overlay_push.sql
-- 2026-09 onboarding/app pass. Everything the client now writes or reads that the schema
-- did not have a home for, plus what the reference-data overlay and push scaffolding need.
-- Every statement is idempotent (add column if not exists / drop constraint if exists) so
-- a project that already ran part of it can replay it.
--
-- Guardrail #3 still holds: nothing here is financial. `estimated_cote_r` is the student's
-- own guess and lives in its own, explicitly named column so it can never be mistaken for
-- the confirmed figures in student_r_score_confirmations (guardrail #2).

-- A ------------------------------------------------------------------------- student_profiles

alter table student_profiles
  add column if not exists interest_ids text[] not null default '{}',   -- goal quiz output
  add column if not exists dec_profile_id text,                          -- SH/SN profile pick
  add column if not exists goal_skipped boolean not null default false,  -- "Passer cette étape"
  add column if not exists estimated_cote_r numeric
    check (estimated_cote_r is null or estimated_cote_r between 15 and 50);

comment on column student_profiles.estimated_cote_r is
  'Student''s own estimate (see src/lib/profile/sync.ts). Never an official figure; those are student_r_score_confirmations rows.';

-- B ------------------------------------------------------------- staging_cegep_programs.type
-- 20260825120000 widened the production table to accept "special" (Tremplin DEC and
-- friends) but left staging on the two-value check, so a "special" row could be scraped
-- and never promoted.

alter table staging_cegep_programs drop constraint if exists staging_cegep_programs_type_check;
alter table staging_cegep_programs add constraint staging_cegep_programs_type_check
  check (type in ('pre_university', 'technical', 'special'));

-- C ---------------------------------------------------------------------- notification_events
-- The client derives events by catalogue slug (the uuid FKs only exist once the seed runs),
-- and an inbox needs a read marker. subject_type was free text; it is now the three values
-- src/lib/notifications/types.ts has always assumed.

alter table notification_events drop constraint if exists notification_events_subject_type_check;
alter table notification_events add constraint notification_events_subject_type_check
  check (subject_type in ('bursary', 'university_program', 'deadline'));
alter table notification_events alter column subject_id drop not null;
alter table notification_events add column if not exists subject_slug text;
alter table notification_events add column if not exists read_at timestamptz;
alter table notification_events drop constraint if exists notification_events_subject_present;
alter table notification_events add constraint notification_events_subject_present
  check (subject_id is not null or subject_slug is not null);
create index if not exists idx_notif_events_user_unread
  on notification_events (user_id) where read_at is null;

-- D ---------------------------------------------------------------------------------- bursaries
-- The client matches on ministerial DEC codes (src/lib/matching/match.ts), which the uuid[]
-- column cannot hold, and every shipped bursary carries its own source URL and deadline
-- precision. `catalog_slug` is the natural key the seed upserts on. application_url becomes
-- nullable: some foundations have no public form and route students to a human.

alter table bursaries add column if not exists catalog_slug text;
create unique index if not exists bursaries_catalog_slug_key on bursaries (catalog_slug);
alter table bursaries add column if not exists eligible_cegep_program_codes text[];
create index if not exists idx_bursaries_eligible_program_codes
  on bursaries using gin (eligible_cegep_program_codes);
alter table bursaries add column if not exists deadline_precision text
  check (deadline_precision is null or deadline_precision in ('day', 'month', 'year'));
alter table bursaries add column if not exists source_url text;
update bursaries set source_url = application_url where source_url is null;
alter table bursaries alter column source_url set not null;              -- guardrail #1
alter table bursaries alter column application_url drop not null;

alter table staging_bursaries
  add column if not exists catalog_slug text,
  add column if not exists eligible_cegep_program_codes text[],
  add column if not exists deadline_precision text,
  add column if not exists source_url text;
alter table staging_bursaries alter column application_url drop not null;

-- E ---------------------------------------------------------------------------------- deadlines
-- src/lib/data/important-dates.ts carries bilingual titles and details, a category, and the
-- university programs a date applies to. Widen the row to hold them so the bundle can be
-- rebuilt from the database without loss.

alter table deadlines add column if not exists catalog_slug text;
create unique index if not exists deadlines_catalog_slug_key on deadlines (catalog_slug);
alter table deadlines
  add column if not exists title_en text,
  add column if not exists detail text,
  add column if not exists detail_en text,
  add column if not exists program_slugs text[],
  add column if not exists category text;
alter table deadlines drop constraint if exists deadlines_category_check;
alter table deadlines add constraint deadlines_category_check
  check (category is null or category in ('cegep', 'university', 'bursary', 'test', 'general'));
alter table deadlines drop constraint if exists deadlines_type_check;
alter table deadlines add constraint deadlines_type_check check (type in
  ('sracq_round', 'sram_round', 'afe_deadline', 'withdrawal_no_penalty',
   'university_admission', 'test', 'bursary', 'other'));

alter table staging_deadlines
  add column if not exists catalog_slug text,
  add column if not exists title_en text,
  add column if not exists detail text,
  add column if not exists detail_en text,
  add column if not exists program_slugs text[],
  add column if not exists category text;
alter table staging_deadlines drop constraint if exists staging_deadlines_type_check;
alter table staging_deadlines add constraint staging_deadlines_type_check check (type in
  ('sracq_round', 'sram_round', 'afe_deadline', 'withdrawal_no_penalty',
   'university_admission', 'test', 'bursary', 'other'));

-- F ----------------------------------------------------------------- generic_program_profiles
-- Ministerial revisions and double-DEC variants (200.B1, 200.11, 300.M0, …) are the same
-- programme as their base code; `aliases` records that instead of duplicating the profile.

alter table generic_program_profiles
  add column if not exists name_en text,
  add column if not exists description_en text,
  add column if not exists aliases text[] not null default '{}';
create index if not exists idx_generic_prog_profiles_aliases
  on generic_program_profiles using gin (aliases);

-- G --------------------------------------------------------------------- push_subscriptions
-- Web Push endpoints, one row per browser. Only read by the service-role sender
-- (scripts/notifications/send-due.ts); students see and delete only their own.

create table if not exists push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade not null,
  endpoint text unique not null,
  p256dh text not null,
  auth text not null,
  user_agent text,
  locale text check (locale is null or locale in ('fr', 'en')),
  created_at timestamptz default now(),
  last_seen_at timestamptz default now()
);
alter table push_subscriptions enable row level security;
drop policy if exists "own subscriptions only" on push_subscriptions;
create policy "own subscriptions only" on push_subscriptions
  for all using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create index if not exists idx_push_subscriptions_user on push_subscriptions (user_id);

-- H ------------------------------------------------------------------------ catalog_versions
-- What /api/reference/version reports. One row per seed or promotion; the newest wins.

create table if not exists catalog_versions (
  version text primary key,
  generated_at timestamptz not null,
  source text not null check (source in ('build-catalog', 'promote')),
  row_counts jsonb
);
alter table catalog_versions enable row level security;
drop policy if exists "public read" on catalog_versions;
create policy "public read" on catalog_versions for select using (true);

