// GENERATED by scripts/data/build-catalog.ts — do not edit by hand.
// Source: src/lib/data/raw/*.json. Regenerate with `npm run build:catalog`.
//
// Institution `id`s are deterministic UUIDv5s shared with supabase/seed/catalog.sql, so a
// client can name a Supabase row without a lookup. Program `id`s are human-readable slugs
// used for routing and for the local-first profile store.

export type CegepSector = "public_french" | "public_english" | "private";
export type CegepProgramType = "pre_university" | "technical" | "special";

export type CatalogCegep = {
  id: string;
  shortCode: string;
  name: string;
  sector: CegepSector;
  admissionService: string;
  websiteUrl: string | null;
};

export type CatalogCegepProgram = {
  id: string;
  cegepShortCode: string;
  code: string;
  name: string;
  type: CegepProgramType;
};

export type CatalogUniversity = {
  id: string;
  shortCode: string;
  name: string;
  websiteUrl: string;
};

export type CatalogUniversityProgram = {
  id: string;
  universityShortCode: string;
  name: string;
  url: string;
};

export const CATALOG_CEGEPS: CatalogCegep[] = [
  {
    "id": "51443ba8-0458-5c0b-8dff-f032d8237ac7",
    "shortCode": "sainte-foy",
    "name": "Cégep de Sainte-Foy",
    "sector": "public_french",
    "admissionService": "SRACQ",
    "websiteUrl": "https://www.csfoy.ca"
  },
  {
    "id": "3f84aa3f-e880-54a2-aff9-58d5e1d391d1",
    "shortCode": "garneau",
    "name": "Cégep Garneau",
    "sector": "public_french",
    "admissionService": "SRACQ",
    "websiteUrl": "https://www.cegepgarneau.ca/"
  },
  {
    "id": "5aa93681-f76e-50af-8d02-b7e3e1f8bcc3",
    "shortCode": "limoilou-charlesbourg",
    "name": "Cégep Limoilou : campus de Charlesbourg",
    "sector": "public_french",
    "admissionService": "SRACQ",
    "websiteUrl": "https://www.cegeplimoilou.ca/"
  },
  {
    "id": "ebdf5752-25e0-5bac-b058-400af26d50e7",
    "shortCode": "limoilou",
    "name": "Cégep Limoilou : campus de Limoilou",
    "sector": "public_french",
    "admissionService": "SRACQ",
    "websiteUrl": "https://www.cegeplimoilou.ca/"
  },
  {
    "id": "39dcfa6a-a660-5772-85a4-ef009173febd",
    "shortCode": "charlevoix",
    "name": "Centre d'études collégiales en Charlevoix",
    "sector": "public_french",
    "admissionService": "SRACQ",
    "websiteUrl": "https://ceccharlevoix.ca/"
  },
  {
    "id": "b3ea194b-0235-569f-a6bd-cc3cd4348eae",
    "shortCode": "champlain-slc",
    "name": "Champlain College: St. Lawrence Campus",
    "sector": "public_english",
    "admissionService": "SRACQ",
    "websiteUrl": null
  },
  {
    "id": "cad091cf-7549-5e4c-b937-f1470adf97f9",
    "shortCode": "bart",
    "name": "Collège Bart (privé)",
    "sector": "private",
    "admissionService": "direct",
    "websiteUrl": null
  },
  {
    "id": "6ceb5719-9834-504a-921f-a6e30b930a00",
    "shortCode": "osullivan-quebec",
    "name": "Collège O'Sullivan de Québec (privé)",
    "sector": "private",
    "admissionService": "direct",
    "websiteUrl": null
  },
  {
    "id": "350efe41-c75b-5b74-960e-396ebefa0ff9",
    "shortCode": "conservatoire-quebec",
    "name": "Conservatoire de musique de Québec",
    "sector": "public_french",
    "admissionService": "direct",
    "websiteUrl": "http://www.conservatoire.gouv.qc.ca/"
  },
  {
    "id": "bc0c824c-6326-595b-9dd2-5b428238ffdf",
    "shortCode": "merici",
    "name": "Mérici Collégial Privé (privé)",
    "sector": "private",
    "admissionService": "direct",
    "websiteUrl": "https://www.merici.ca/"
  },
  {
    "id": "b27be812-7eac-55b1-8232-4317981295d8",
    "shortCode": "notre-dame-de-foy",
    "name": "Notre-Dame-de-Foy (privé)",
    "sector": "private",
    "admissionService": "direct",
    "websiteUrl": null
  }
];

export const CATALOG_CEGEP_PROGRAMS: CatalogCegepProgram[] = [
  {
    "id": "sainte-foy-510-a0",
    "cegepShortCode": "sainte-foy",
    "code": "510.A0",
    "name": "Arts visuels",
    "type": "pre_university"
  },
  {
    "id": "sainte-foy-500-ag",
    "cegepShortCode": "sainte-foy",
    "code": "500.AG",
    "name": "Arts, lettres et communication : option Cinéma",
    "type": "pre_university"
  },
  {
    "id": "sainte-foy-500-al",
    "cegepShortCode": "sainte-foy",
    "code": "500.AL",
    "name": "Arts, lettres et communication : option Langues",
    "type": "pre_university"
  },
  {
    "id": "sainte-foy-500-ah",
    "cegepShortCode": "sainte-foy",
    "code": "500.AH",
    "name": "Arts, lettres et communication : option Littérature",
    "type": "pre_university"
  },
  {
    "id": "sainte-foy-561-bb",
    "cegepShortCode": "sainte-foy",
    "code": "561.BB",
    "name": "Danse-interprétation contemporaine",
    "type": "technical"
  },
  {
    "id": "sainte-foy-570-g0",
    "cegepShortCode": "sainte-foy",
    "code": "570.G0",
    "name": "Graphisme",
    "type": "technical"
  },
  {
    "id": "sainte-foy-700-b0",
    "cegepShortCode": "sainte-foy",
    "code": "700.B0",
    "name": "Histoire et civilisation",
    "type": "pre_university"
  },
  {
    "id": "sainte-foy-501-a0",
    "cegepShortCode": "sainte-foy",
    "code": "501.A0",
    "name": "Musique",
    "type": "pre_university"
  },
  {
    "id": "sainte-foy-200-b1",
    "cegepShortCode": "sainte-foy",
    "code": "200.B1",
    "name": "Sciences de la nature",
    "type": "pre_university"
  },
  {
    "id": "sainte-foy-200-16",
    "cegepShortCode": "sainte-foy",
    "code": "200.16",
    "name": "Sciences de la nature et Arts, lettres et communication",
    "type": "pre_university"
  },
  {
    "id": "sainte-foy-200-11",
    "cegepShortCode": "sainte-foy",
    "code": "200.11",
    "name": "Sciences de la nature et Musique",
    "type": "pre_university"
  },
  {
    "id": "sainte-foy-300-m0",
    "cegepShortCode": "sainte-foy",
    "code": "300.M0",
    "name": "Sciences humaines",
    "type": "pre_university"
  },
  {
    "id": "sainte-foy-300-m1",
    "cegepShortCode": "sainte-foy",
    "code": "300.M1",
    "name": "Sciences humaines avec mathématiques supplémentaires",
    "type": "pre_university"
  },
  {
    "id": "sainte-foy-300-16",
    "cegepShortCode": "sainte-foy",
    "code": "300.16",
    "name": "Sciences humaines et Arts, lettres et communication",
    "type": "pre_university"
  },
  {
    "id": "sainte-foy-300-11",
    "cegepShortCode": "sainte-foy",
    "code": "300.11",
    "name": "Sciences humaines et Musique",
    "type": "pre_university"
  },
  {
    "id": "sainte-foy-700-a1",
    "cegepShortCode": "sainte-foy",
    "code": "700.A1",
    "name": "Sciences, lettres et arts",
    "type": "pre_university"
  },
  {
    "id": "sainte-foy-180-a0",
    "cegepShortCode": "sainte-foy",
    "code": "180.A0",
    "name": "Soins infirmiers",
    "type": "technical"
  },
  {
    "id": "sainte-foy-181-a1",
    "cegepShortCode": "sainte-foy",
    "code": "181.A1",
    "name": "Soins préhospitaliers d'urgence",
    "type": "technical"
  },
  {
    "id": "sainte-foy-410-g0",
    "cegepShortCode": "sainte-foy",
    "code": "410.G0",
    "name": "Techniques d’administration et de gestion",
    "type": "technical"
  },
  {
    "id": "sainte-foy-322-a1",
    "cegepShortCode": "sainte-foy",
    "code": "322.A1",
    "name": "Techniques d’éducation à l’enfance",
    "type": "technical"
  },
  {
    "id": "sainte-foy-351-a1",
    "cegepShortCode": "sainte-foy",
    "code": "351.A1",
    "name": "Techniques d'éducation spécialisée",
    "type": "technical"
  },
  {
    "id": "sainte-foy-141-a0",
    "cegepShortCode": "sainte-foy",
    "code": "141.A0",
    "name": "Techniques d'inhalothérapie",
    "type": "technical"
  },
  {
    "id": "sainte-foy-582-a1",
    "cegepShortCode": "sainte-foy",
    "code": "582.A1",
    "name": "Techniques d'intégration multimédia",
    "type": "technical"
  },
  {
    "id": "sainte-foy-145-c0",
    "cegepShortCode": "sainte-foy",
    "code": "145.C0",
    "name": "Techniques de bioécologie",
    "type": "technical"
  },
  {
    "id": "sainte-foy-570-d0",
    "cegepShortCode": "sainte-foy",
    "code": "570.D0",
    "name": "Techniques de design de présentation",
    "type": "technical"
  },
  {
    "id": "sainte-foy-570-c0",
    "cegepShortCode": "sainte-foy",
    "code": "570.C0",
    "name": "Techniques de design de produits (design industriel)",
    "type": "technical"
  },
  {
    "id": "sainte-foy-420-b0",
    "cegepShortCode": "sainte-foy",
    "code": "420.B0",
    "name": "Techniques de l'informatique",
    "type": "technical"
  },
  {
    "id": "sainte-foy-410-f0",
    "cegepShortCode": "sainte-foy",
    "code": "410.F0",
    "name": "Techniques de services financiers et d'assurances",
    "type": "technical"
  },
  {
    "id": "sainte-foy-388-a1",
    "cegepShortCode": "sainte-foy",
    "code": "388.A1",
    "name": "Techniques de travail social",
    "type": "technical"
  },
  {
    "id": "sainte-foy-140-c0",
    "cegepShortCode": "sainte-foy",
    "code": "140.C0",
    "name": "Technologie d'analyses biomédicales",
    "type": "technical"
  },
  {
    "id": "sainte-foy-142-g0",
    "cegepShortCode": "sainte-foy",
    "code": "142.G0",
    "name": "Technologie de l'échographie médicale",
    "type": "technical"
  },
  {
    "id": "sainte-foy-142-f0",
    "cegepShortCode": "sainte-foy",
    "code": "142.F0",
    "name": "Technologie de médecine nucléaire",
    "type": "technical"
  },
  {
    "id": "sainte-foy-142-d0",
    "cegepShortCode": "sainte-foy",
    "code": "142.D0",
    "name": "Technologie de radio-oncologie",
    "type": "technical"
  },
  {
    "id": "sainte-foy-142-h0",
    "cegepShortCode": "sainte-foy",
    "code": "142.H0",
    "name": "Technologie de radiodiagnostic",
    "type": "technical"
  },
  {
    "id": "sainte-foy-190-b0",
    "cegepShortCode": "sainte-foy",
    "code": "190.B0",
    "name": "Technologie forestière",
    "type": "technical"
  },
  {
    "id": "sainte-foy-081-06",
    "cegepShortCode": "sainte-foy",
    "code": "081.06",
    "name": "Tremplin DEC",
    "type": "special"
  },
  {
    "id": "garneau-500-ag",
    "cegepShortCode": "garneau",
    "code": "500.AG",
    "name": "Arts, lettres et communication : option Cinéma",
    "type": "pre_university"
  },
  {
    "id": "garneau-500-al",
    "cegepShortCode": "garneau",
    "code": "500.AL",
    "name": "Arts, lettres et communication : option Langues",
    "type": "pre_university"
  },
  {
    "id": "garneau-500-ah",
    "cegepShortCode": "garneau",
    "code": "500.AH",
    "name": "Arts, lettres et communication : option Littérature",
    "type": "pre_university"
  },
  {
    "id": "garneau-500-ae",
    "cegepShortCode": "garneau",
    "code": "500.AE",
    "name": "Arts, lettres et communication : option Multidisciplinaire",
    "type": "pre_university"
  },
  {
    "id": "garneau-200-z1",
    "cegepShortCode": "garneau",
    "code": "200.Z1",
    "name": "Baccalauréat international : Sciences de la nature",
    "type": "pre_university"
  },
  {
    "id": "garneau-410-a1",
    "cegepShortCode": "garneau",
    "code": "410.A1",
    "name": "Gestion des opérations et de la chaîne logistique",
    "type": "technical"
  },
  {
    "id": "garneau-160-a0",
    "cegepShortCode": "garneau",
    "code": "160.A0",
    "name": "Optique et lunetterie",
    "type": "technical"
  },
  {
    "id": "garneau-200-b1",
    "cegepShortCode": "garneau",
    "code": "200.B1",
    "name": "Sciences de la nature",
    "type": "pre_university"
  },
  {
    "id": "garneau-300-m0",
    "cegepShortCode": "garneau",
    "code": "300.M0",
    "name": "Sciences humaines",
    "type": "pre_university"
  },
  {
    "id": "garneau-300-m1",
    "cegepShortCode": "garneau",
    "code": "300.M1",
    "name": "Sciences humaines avec mathématiques supplémentaires",
    "type": "pre_university"
  },
  {
    "id": "garneau-180-a0",
    "cegepShortCode": "garneau",
    "code": "180.A0",
    "name": "Soins infirmiers",
    "type": "technical"
  },
  {
    "id": "garneau-410-g0",
    "cegepShortCode": "garneau",
    "code": "410.G0",
    "name": "Techniques d’administration et de gestion",
    "type": "technical"
  },
  {
    "id": "garneau-111-b0",
    "cegepShortCode": "garneau",
    "code": "111.B0",
    "name": "Techniques d'hygiène dentaire",
    "type": "technical"
  },
  {
    "id": "garneau-310-b1",
    "cegepShortCode": "garneau",
    "code": "310.B1",
    "name": "Techniques d’intervention en criminologie",
    "type": "technical"
  },
  {
    "id": "garneau-570-e0",
    "cegepShortCode": "garneau",
    "code": "570.E0",
    "name": "Techniques de design d'intérieur",
    "type": "technical"
  },
  {
    "id": "garneau-420-b0",
    "cegepShortCode": "garneau",
    "code": "420.B0",
    "name": "Techniques de l'informatique",
    "type": "technical"
  },
  {
    "id": "garneau-393-b0",
    "cegepShortCode": "garneau",
    "code": "393.B0",
    "name": "Techniques de la documentation",
    "type": "technical"
  },
  {
    "id": "garneau-144-a1",
    "cegepShortCode": "garneau",
    "code": "144.A1",
    "name": "Techniques de physiothérapie",
    "type": "technical"
  },
  {
    "id": "garneau-310-c0",
    "cegepShortCode": "garneau",
    "code": "310.C0",
    "name": "Techniques juridiques",
    "type": "technical"
  },
  {
    "id": "garneau-310-a0",
    "cegepShortCode": "garneau",
    "code": "310.A0",
    "name": "Techniques policières",
    "type": "technical"
  },
  {
    "id": "garneau-081-06",
    "cegepShortCode": "garneau",
    "code": "081.06",
    "name": "Tremplin DEC",
    "type": "special"
  },
  {
    "id": "garneau-081-05",
    "cegepShortCode": "garneau",
    "code": "081.05",
    "name": "Tremplin DEC - Premières Nations",
    "type": "special"
  },
  {
    "id": "limoilou-charlesbourg-430-b0",
    "cegepShortCode": "limoilou-charlesbourg",
    "code": "430.B0",
    "name": "Gestion d'un établissement de restauration",
    "type": "technical"
  },
  {
    "id": "limoilou-charlesbourg-200-b1",
    "cegepShortCode": "limoilou-charlesbourg",
    "code": "200.B1",
    "name": "Sciences de la nature",
    "type": "pre_university"
  },
  {
    "id": "limoilou-charlesbourg-200-12",
    "cegepShortCode": "limoilou-charlesbourg",
    "code": "200.12",
    "name": "Sciences de la nature et Sciences humaines",
    "type": "pre_university"
  },
  {
    "id": "limoilou-charlesbourg-300-m0",
    "cegepShortCode": "limoilou-charlesbourg",
    "code": "300.M0",
    "name": "Sciences humaines",
    "type": "pre_university"
  },
  {
    "id": "limoilou-charlesbourg-300-m1",
    "cegepShortCode": "limoilou-charlesbourg",
    "code": "300.M1",
    "name": "Sciences humaines avec mathématiques supplémentaires",
    "type": "pre_university"
  },
  {
    "id": "limoilou-charlesbourg-120-a0",
    "cegepShortCode": "limoilou-charlesbourg",
    "code": "120.A0",
    "name": "Techniques de diététique",
    "type": "technical"
  },
  {
    "id": "limoilou-charlesbourg-430-a0",
    "cegepShortCode": "limoilou-charlesbourg",
    "code": "430.A0",
    "name": "Techniques de gestion hôtelière",
    "type": "technical"
  },
  {
    "id": "limoilou-charlesbourg-414-a0",
    "cegepShortCode": "limoilou-charlesbourg",
    "code": "414.A0",
    "name": "Techniques de tourisme",
    "type": "technical"
  },
  {
    "id": "limoilou-charlesbourg-221-b0",
    "cegepShortCode": "limoilou-charlesbourg",
    "code": "221.B0",
    "name": "Technologie du génie civil",
    "type": "technical"
  },
  {
    "id": "limoilou-charlesbourg-221-c0",
    "cegepShortCode": "limoilou-charlesbourg",
    "code": "221.C0",
    "name": "Technologie du génie du bâtiment (mécanique du bâtiment)",
    "type": "technical"
  },
  {
    "id": "limoilou-charlesbourg-081-06",
    "cegepShortCode": "limoilou-charlesbourg",
    "code": "081.06",
    "name": "Tremplin DEC",
    "type": "special"
  },
  {
    "id": "limoilou-561-d0",
    "cegepShortCode": "limoilou",
    "code": "561.D0",
    "name": "Arts du cirque",
    "type": "technical"
  },
  {
    "id": "limoilou-510-a0",
    "cegepShortCode": "limoilou",
    "code": "510.A0",
    "name": "Arts visuels",
    "type": "pre_university"
  },
  {
    "id": "limoilou-500-al",
    "cegepShortCode": "limoilou",
    "code": "500.AL",
    "name": "Arts, lettres et communication : option Langues",
    "type": "pre_university"
  },
  {
    "id": "limoilou-500-aj",
    "cegepShortCode": "limoilou",
    "code": "500.AJ",
    "name": "Arts, lettres et communication : option Médias",
    "type": "pre_university"
  },
  {
    "id": "limoilou-500-ak",
    "cegepShortCode": "limoilou",
    "code": "500.AK",
    "name": "Arts, lettres et communication : option Théâtre",
    "type": "pre_university"
  },
  {
    "id": "limoilou-574-c0",
    "cegepShortCode": "limoilou",
    "code": "574.C0",
    "name": "Production 3D et synthèse d’images",
    "type": "technical"
  },
  {
    "id": "limoilou-200-b1",
    "cegepShortCode": "limoilou",
    "code": "200.B1",
    "name": "Sciences de la nature",
    "type": "pre_university"
  },
  {
    "id": "limoilou-200-12",
    "cegepShortCode": "limoilou",
    "code": "200.12",
    "name": "Sciences de la nature et Sciences humaines",
    "type": "pre_university"
  },
  {
    "id": "limoilou-300-m0",
    "cegepShortCode": "limoilou",
    "code": "300.M0",
    "name": "Sciences humaines",
    "type": "pre_university"
  },
  {
    "id": "limoilou-300-m1",
    "cegepShortCode": "limoilou",
    "code": "300.M1",
    "name": "Sciences humaines avec mathématiques supplémentaires",
    "type": "pre_university"
  },
  {
    "id": "limoilou-300-16",
    "cegepShortCode": "limoilou",
    "code": "300.16",
    "name": "Sciences humaines et Arts, lettres et communication",
    "type": "pre_university"
  },
  {
    "id": "limoilou-200-c1",
    "cegepShortCode": "limoilou",
    "code": "200.C1",
    "name": "Sciences, informatique et mathématique",
    "type": "pre_university"
  },
  {
    "id": "limoilou-180-a0",
    "cegepShortCode": "limoilou",
    "code": "180.A0",
    "name": "Soins infirmiers",
    "type": "technical"
  },
  {
    "id": "limoilou-410-g0",
    "cegepShortCode": "limoilou",
    "code": "410.G0",
    "name": "Techniques d’administration et de gestion",
    "type": "technical"
  },
  {
    "id": "limoilou-241-a0",
    "cegepShortCode": "limoilou",
    "code": "241.A0",
    "name": "Techniques de génie mécanique",
    "type": "technical"
  },
  {
    "id": "limoilou-420-b0",
    "cegepShortCode": "limoilou",
    "code": "420.B0",
    "name": "Techniques de l'informatique",
    "type": "technical"
  },
  {
    "id": "limoilou-165-a0",
    "cegepShortCode": "limoilou",
    "code": "165.A0",
    "name": "Techniques de pharmacie",
    "type": "technical"
  },
  {
    "id": "limoilou-573-aa",
    "cegepShortCode": "limoilou",
    "code": "573.AA",
    "name": "Techniques des métiers d'art : Céramique",
    "type": "technical"
  },
  {
    "id": "limoilou-573-ab",
    "cegepShortCode": "limoilou",
    "code": "573.AB",
    "name": "Techniques des métiers d'art : Construction textile",
    "type": "technical"
  },
  {
    "id": "limoilou-573-ac",
    "cegepShortCode": "limoilou",
    "code": "573.AC",
    "name": "Techniques des métiers d'art : Ébénisterie artisanale",
    "type": "technical"
  },
  {
    "id": "limoilou-573-ae",
    "cegepShortCode": "limoilou",
    "code": "573.AE",
    "name": "Techniques des métiers d'art : Joaillerie",
    "type": "technical"
  },
  {
    "id": "limoilou-573-af",
    "cegepShortCode": "limoilou",
    "code": "573.AF",
    "name": "Techniques des métiers d'art : Lutherie",
    "type": "technical"
  },
  {
    "id": "limoilou-573-ah",
    "cegepShortCode": "limoilou",
    "code": "573.AH",
    "name": "Techniques des métiers d'arts : Sculpture",
    "type": "technical"
  },
  {
    "id": "limoilou-243-h0",
    "cegepShortCode": "limoilou",
    "code": "243.H0",
    "name": "Technologie de l’électronique : Audiovisuel",
    "type": "technical"
  },
  {
    "id": "limoilou-230-b0",
    "cegepShortCode": "limoilou",
    "code": "230.B0",
    "name": "Technologie de la géomatique",
    "type": "technical"
  },
  {
    "id": "limoilou-243-d0",
    "cegepShortCode": "limoilou",
    "code": "243.D0",
    "name": "Technologie du génie électrique : automatisation et contrôle",
    "type": "technical"
  },
  {
    "id": "limoilou-243-g0",
    "cegepShortCode": "limoilou",
    "code": "243.G0",
    "name": "Technologie du génie électrique : Électronique programmable",
    "type": "technical"
  },
  {
    "id": "limoilou-243-f0",
    "cegepShortCode": "limoilou",
    "code": "243.F0",
    "name": "Technologie du génie électrique : Réseaux et télécommunications",
    "type": "technical"
  },
  {
    "id": "limoilou-235-b0",
    "cegepShortCode": "limoilou",
    "code": "235.B0",
    "name": "Technologie du génie industriel",
    "type": "technical"
  },
  {
    "id": "limoilou-081-06",
    "cegepShortCode": "limoilou",
    "code": "081.06",
    "name": "Tremplin DEC",
    "type": "special"
  },
  {
    "id": "charlevoix-200-b1",
    "cegepShortCode": "charlevoix",
    "code": "200.B1",
    "name": "Sciences de la nature",
    "type": "pre_university"
  },
  {
    "id": "charlevoix-300-m0",
    "cegepShortCode": "charlevoix",
    "code": "300.M0",
    "name": "Sciences humaines",
    "type": "pre_university"
  },
  {
    "id": "charlevoix-300-m1",
    "cegepShortCode": "charlevoix",
    "code": "300.M1",
    "name": "Sciences humaines avec mathématiques supplémentaires",
    "type": "pre_university"
  },
  {
    "id": "charlevoix-180-a0",
    "cegepShortCode": "charlevoix",
    "code": "180.A0",
    "name": "Soins infirmiers",
    "type": "technical"
  },
  {
    "id": "charlevoix-410-g0",
    "cegepShortCode": "charlevoix",
    "code": "410.G0",
    "name": "Techniques d’administration et de gestion",
    "type": "technical"
  },
  {
    "id": "charlevoix-351-a1",
    "cegepShortCode": "charlevoix",
    "code": "351.A1",
    "name": "Techniques d'éducation spécialisée",
    "type": "technical"
  },
  {
    "id": "charlevoix-081-06",
    "cegepShortCode": "charlevoix",
    "code": "081.06",
    "name": "Tremplin DEC",
    "type": "special"
  },
  {
    "id": "champlain-slc-500-ae",
    "cegepShortCode": "champlain-slc",
    "code": "500.AE",
    "name": "Arts, lettres et communication : option Multidisciplinaire",
    "type": "pre_university"
  },
  {
    "id": "champlain-slc-200-b1",
    "cegepShortCode": "champlain-slc",
    "code": "200.B1",
    "name": "Sciences de la nature",
    "type": "pre_university"
  },
  {
    "id": "champlain-slc-200-16",
    "cegepShortCode": "champlain-slc",
    "code": "200.16",
    "name": "Sciences de la nature et Arts, lettres et communication",
    "type": "pre_university"
  },
  {
    "id": "champlain-slc-200-12",
    "cegepShortCode": "champlain-slc",
    "code": "200.12",
    "name": "Sciences de la nature et Sciences humaines",
    "type": "pre_university"
  },
  {
    "id": "champlain-slc-300-m0",
    "cegepShortCode": "champlain-slc",
    "code": "300.M0",
    "name": "Sciences humaines",
    "type": "pre_university"
  },
  {
    "id": "champlain-slc-300-m1",
    "cegepShortCode": "champlain-slc",
    "code": "300.M1",
    "name": "Sciences humaines avec mathématiques supplémentaires",
    "type": "pre_university"
  },
  {
    "id": "champlain-slc-300-16",
    "cegepShortCode": "champlain-slc",
    "code": "300.16",
    "name": "Sciences humaines et Arts, lettres et communication",
    "type": "pre_university"
  },
  {
    "id": "champlain-slc-410-g0",
    "cegepShortCode": "champlain-slc",
    "code": "410.G0",
    "name": "Techniques d’administration et de gestion",
    "type": "technical"
  },
  {
    "id": "champlain-slc-414-a0",
    "cegepShortCode": "champlain-slc",
    "code": "414.A0",
    "name": "Techniques de tourisme",
    "type": "technical"
  },
  {
    "id": "champlain-slc-081-06",
    "cegepShortCode": "champlain-slc",
    "code": "081.06",
    "name": "Tremplin DEC",
    "type": "special"
  },
  {
    "id": "bart-570-g0",
    "cegepShortCode": "bart",
    "code": "570.G0",
    "name": "Graphisme",
    "type": "technical"
  },
  {
    "id": "bart-574-c0",
    "cegepShortCode": "bart",
    "code": "574.C0",
    "name": "Production 3D et synthèse d’images",
    "type": "technical"
  },
  {
    "id": "bart-589-c0",
    "cegepShortCode": "bart",
    "code": "589.C0",
    "name": "Techniques cinématographiques et télévisuelles",
    "type": "technical"
  },
  {
    "id": "bart-410-g0",
    "cegepShortCode": "bart",
    "code": "410.G0",
    "name": "Techniques d’administration et de gestion",
    "type": "technical"
  },
  {
    "id": "bart-420-b0",
    "cegepShortCode": "bart",
    "code": "420.B0",
    "name": "Techniques de l'informatique",
    "type": "technical"
  },
  {
    "id": "bart-310-c0",
    "cegepShortCode": "bart",
    "code": "310.C0",
    "name": "Techniques juridiques",
    "type": "technical"
  },
  {
    "id": "osullivan-quebec-574-c0",
    "cegepShortCode": "osullivan-quebec",
    "code": "574.C0",
    "name": "Production 3D et synthèse d’images",
    "type": "technical"
  },
  {
    "id": "osullivan-quebec-410-g0",
    "cegepShortCode": "osullivan-quebec",
    "code": "410.G0",
    "name": "Techniques d’administration et de gestion",
    "type": "technical"
  },
  {
    "id": "osullivan-quebec-420-b0",
    "cegepShortCode": "osullivan-quebec",
    "code": "420.B0",
    "name": "Techniques de l'informatique",
    "type": "technical"
  },
  {
    "id": "osullivan-quebec-410-f0",
    "cegepShortCode": "osullivan-quebec",
    "code": "410.F0",
    "name": "Techniques de services financiers et d'assurances",
    "type": "technical"
  },
  {
    "id": "conservatoire-quebec-501-a0",
    "cegepShortCode": "conservatoire-quebec",
    "code": "501.A0",
    "name": "Musique",
    "type": "pre_university"
  },
  {
    "id": "merici-144-f0",
    "cegepShortCode": "merici",
    "code": "144.F0",
    "name": "Orthèses, prothèses et soins orthopédiques",
    "type": "technical"
  },
  {
    "id": "merici-200-b1",
    "cegepShortCode": "merici",
    "code": "200.B1",
    "name": "Sciences de la nature",
    "type": "pre_university"
  },
  {
    "id": "merici-300-m0",
    "cegepShortCode": "merici",
    "code": "300.M0",
    "name": "Sciences humaines",
    "type": "pre_university"
  },
  {
    "id": "merici-410-g0",
    "cegepShortCode": "merici",
    "code": "410.G0",
    "name": "Techniques d’administration et de gestion",
    "type": "technical"
  },
  {
    "id": "merici-351-a1",
    "cegepShortCode": "merici",
    "code": "351.A1",
    "name": "Techniques d'éducation spécialisée",
    "type": "technical"
  },
  {
    "id": "merici-430-a0",
    "cegepShortCode": "merici",
    "code": "430.A0",
    "name": "Techniques de gestion hôtelière",
    "type": "technical"
  },
  {
    "id": "merici-280-f0",
    "cegepShortCode": "merici",
    "code": "280.F0",
    "name": "Techniques de pilotage d'aéronefs",
    "type": "technical"
  },
  {
    "id": "merici-414-a0",
    "cegepShortCode": "merici",
    "code": "414.A0",
    "name": "Techniques de tourisme",
    "type": "technical"
  },
  {
    "id": "merici-081-06",
    "cegepShortCode": "merici",
    "code": "081.06",
    "name": "Tremplin DEC",
    "type": "special"
  },
  {
    "id": "notre-dame-de-foy-571-c0",
    "cegepShortCode": "notre-dame-de-foy",
    "code": "571.C0",
    "name": "Commercialisation de la mode",
    "type": "technical"
  },
  {
    "id": "notre-dame-de-foy-571-a0",
    "cegepShortCode": "notre-dame-de-foy",
    "code": "571.A0",
    "name": "Design de mode",
    "type": "technical"
  },
  {
    "id": "notre-dame-de-foy-501-a0",
    "cegepShortCode": "notre-dame-de-foy",
    "code": "501.A0",
    "name": "Musique",
    "type": "pre_university"
  },
  {
    "id": "notre-dame-de-foy-200-b1",
    "cegepShortCode": "notre-dame-de-foy",
    "code": "200.B1",
    "name": "Sciences de la nature",
    "type": "pre_university"
  },
  {
    "id": "notre-dame-de-foy-200-11",
    "cegepShortCode": "notre-dame-de-foy",
    "code": "200.11",
    "name": "Sciences de la nature et Musique",
    "type": "pre_university"
  },
  {
    "id": "notre-dame-de-foy-300-m0",
    "cegepShortCode": "notre-dame-de-foy",
    "code": "300.M0",
    "name": "Sciences humaines",
    "type": "pre_university"
  },
  {
    "id": "notre-dame-de-foy-180-a0",
    "cegepShortCode": "notre-dame-de-foy",
    "code": "180.A0",
    "name": "Soins infirmiers",
    "type": "technical"
  },
  {
    "id": "notre-dame-de-foy-181-a1",
    "cegepShortCode": "notre-dame-de-foy",
    "code": "181.A1",
    "name": "Soins préhospitaliers d'urgence",
    "type": "technical"
  },
  {
    "id": "notre-dame-de-foy-322-a1",
    "cegepShortCode": "notre-dame-de-foy",
    "code": "322.A1",
    "name": "Techniques d’éducation à l’enfance",
    "type": "technical"
  },
  {
    "id": "notre-dame-de-foy-311-a0",
    "cegepShortCode": "notre-dame-de-foy",
    "code": "311.A0",
    "name": "Techniques de sécurité incendie (après un DEP)",
    "type": "technical"
  },
  {
    "id": "notre-dame-de-foy-171-a0",
    "cegepShortCode": "notre-dame-de-foy",
    "code": "171.A0",
    "name": "Techniques de thanatologie",
    "type": "technical"
  },
  {
    "id": "notre-dame-de-foy-310-a0",
    "cegepShortCode": "notre-dame-de-foy",
    "code": "310.A0",
    "name": "Techniques policières",
    "type": "technical"
  },
  {
    "id": "notre-dame-de-foy-551-a0",
    "cegepShortCode": "notre-dame-de-foy",
    "code": "551.A0",
    "name": "Techniques professionnelles de musique et de chanson",
    "type": "technical"
  },
  {
    "id": "notre-dame-de-foy-221-d0",
    "cegepShortCode": "notre-dame-de-foy",
    "code": "221.D0",
    "name": "Technologie de l'estimation et de l'évaluation en bâtiment",
    "type": "technical"
  }
];

export const CATALOG_UNIVERSITIES: CatalogUniversity[] = [
  {
    "id": "82bc5c92-1ef9-5118-b62b-b7b2e6ab9e7b",
    "shortCode": "concordia",
    "name": "Concordia University",
    "websiteUrl": "https://www.concordia.ca/admissions.html"
  },
  {
    "id": "1388f696-3143-553e-9f11-f46951c56eba",
    "shortCode": "hec",
    "name": "HEC Montréal",
    "websiteUrl": "https://www.hec.ca/programmes/"
  },
  {
    "id": "8f153505-7527-5b5f-a306-a7a91379ff8f",
    "shortCode": "mcgill",
    "name": "McGill University",
    "websiteUrl": "https://www.mcgill.ca/undergraduate-admissions/"
  },
  {
    "id": "6763b2af-bed2-5858-b783-b3b6839c74e3",
    "shortCode": "polymtl",
    "name": "Polytechnique Montréal",
    "websiteUrl": "https://www.polymtl.ca/futur/"
  },
  {
    "id": "d0005784-1e3f-5471-8cbf-cf190e058ef0",
    "shortCode": "udem",
    "name": "Université de Montréal",
    "websiteUrl": "https://admission.umontreal.ca/"
  },
  {
    "id": "f36e069d-efbc-5d00-994a-a0ebeb15a526",
    "shortCode": "uqam",
    "name": "Université du Québec à Montréal (UQAM)",
    "websiteUrl": "https://etudier.uqam.ca/"
  },
  {
    "id": "dd91cd04-ef58-566a-9b17-1c71e6b5f8fa",
    "shortCode": "ulaval",
    "name": "Université Laval",
    "websiteUrl": "https://www.ulaval.ca/etudes/programmes"
  }
];

export const CATALOG_UNIVERSITY_PROGRAMS: CatalogUniversityProgram[] = [
  {
    "id": "concordia-accountancy-bcomm",
    "universityShortCode": "concordia",
    "name": "Accountancy (BComm)",
    "url": "https://www.concordia.ca/academics/undergraduate/accountancy.html"
  },
  {
    "id": "concordia-accountancy-cert",
    "universityShortCode": "concordia",
    "name": "Accountancy (Cert)",
    "url": "https://www.concordia.ca/academics/undergraduate/accountancy-cert.html"
  },
  {
    "id": "concordia-acting-for-the-theatre-bfa",
    "universityShortCode": "concordia",
    "name": "Acting for the Theatre (BFA)",
    "url": "https://www.concordia.ca/academics/undergraduate/acting-theatre.html"
  },
  {
    "id": "concordia-actuarial-mathematics-ba-bsc",
    "universityShortCode": "concordia",
    "name": "Actuarial Mathematics (BA, BSc)",
    "url": "https://www.concordia.ca/academics/undergraduate/actuarial-mathematics.html"
  },
  {
    "id": "concordia-actuarial-mathematics-finance-ba-bsc",
    "universityShortCode": "concordia",
    "name": "Actuarial Mathematics/Finance (BA, BSc)",
    "url": "https://www.concordia.ca/academics/undergraduate/actuarial-mathematics-finance.html"
  },
  {
    "id": "concordia-adult-education-cert",
    "universityShortCode": "concordia",
    "name": "Adult Education (Cert)",
    "url": "https://www.concordia.ca/academics/undergraduate/adult-education.html"
  },
  {
    "id": "concordia-aerospace-engineering-beng",
    "universityShortCode": "concordia",
    "name": "Aerospace Engineering (BEng)",
    "url": "https://www.concordia.ca/academics/undergraduate/aerospace-engineering.html"
  },
  {
    "id": "concordia-anthropology-ba",
    "universityShortCode": "concordia",
    "name": "Anthropology (BA)",
    "url": "https://www.concordia.ca/academics/undergraduate/anthropology.html"
  },
  {
    "id": "concordia-anthropology-and-sociology-ba",
    "universityShortCode": "concordia",
    "name": "Anthropology and Sociology (BA)",
    "url": "https://www.concordia.ca/academics/undergraduate/anthropology-and-sociology.html"
  },
  {
    "id": "concordia-art-education-a-visual-arts-bfa",
    "universityShortCode": "concordia",
    "name": "Art Education â Visual Arts (BFA)",
    "url": "https://www.concordia.ca/academics/undergraduate/art-education.html"
  },
  {
    "id": "concordia-art-history-bfa",
    "universityShortCode": "concordia",
    "name": "Art History (BFA)",
    "url": "https://www.concordia.ca/academics/undergraduate/art-history.html"
  },
  {
    "id": "concordia-art-history-and-film-studies-bfa",
    "universityShortCode": "concordia",
    "name": "Art History and Film Studies (BFA)",
    "url": "https://www.concordia.ca/academics/undergraduate/art-history-filmstudiesbfa.html"
  },
  {
    "id": "concordia-art-history-and-studio-art-bfa",
    "universityShortCode": "concordia",
    "name": "Art History and Studio Art (BFA)",
    "url": "https://www.concordia.ca/academics/undergraduate/art-history-studio-art.html"
  },
  {
    "id": "concordia-arts-and-science-cert",
    "universityShortCode": "concordia",
    "name": "Arts and Science (Cert)",
    "url": "https://www.concordia.ca/academics/undergraduate/arts-science.html"
  },
  {
    "id": "concordia-assurance-fraud-prevention-and-investigative-services",
    "universityShortCode": "concordia",
    "name": "Assurance, Fraud Prevention and Investigative Services",
    "url": "https://www.concordia.ca/academics/undergraduate/assurance-fraud-prevention.html"
  },
  {
    "id": "concordia-athletic-therapy-bsc",
    "universityShortCode": "concordia",
    "name": "Athletic Therapy (BSc)",
    "url": "https://www.concordia.ca/academics/undergraduate/athletic-therapy.html"
  },
  {
    "id": "concordia-a-tudes-frana-aises-french-studies-ba-cert",
    "universityShortCode": "concordia",
    "name": "Ãtudes franÃ§aises (French Studies) (BA, Cert)",
    "url": "https://www.concordia.ca/academics/undergraduate/etudes-francaises.html"
  },
  {
    "id": "concordia-biochemistry-bsc",
    "universityShortCode": "concordia",
    "name": "Biochemistry (BSc)",
    "url": "https://www.concordia.ca/academics/undergraduate/biochemistry.html"
  },
  {
    "id": "concordia-biology-bsc",
    "universityShortCode": "concordia",
    "name": "Biology (BSc)",
    "url": "https://www.concordia.ca/academics/undergraduate/biology.html"
  },
  {
    "id": "concordia-biophysics",
    "universityShortCode": "concordia",
    "name": "Biophysics",
    "url": "https://www.concordia.ca/academics/undergraduate/biophysics.html"
  },
  {
    "id": "concordia-black-and-african-diaspora-studies-in-the-canadian-context-cert",
    "universityShortCode": "concordia",
    "name": "Black and African Diaspora Studies in the Canadian Context (Cert)",
    "url": "https://www.concordia.ca/academics/undergraduate/black-african-diaspora-studies.html"
  },
  {
    "id": "concordia-building-engineering-beng",
    "universityShortCode": "concordia",
    "name": "Building Engineering (BEng)",
    "url": "https://www.concordia.ca/academics/undergraduate/building-engineering.html"
  },
  {
    "id": "concordia-business-analytics-bcomm",
    "universityShortCode": "concordia",
    "name": "Business Analytics (BComm)",
    "url": "https://www.concordia.ca/academics/undergraduate/business-analytics.html"
  },
  {
    "id": "concordia-business-studies-cert",
    "universityShortCode": "concordia",
    "name": "Business Studies (Cert)",
    "url": "https://www.concordia.ca/academics/undergraduate/business-studies.html"
  },
  {
    "id": "concordia-business-technology-management-bcomm",
    "universityShortCode": "concordia",
    "name": "Business Technology Management (BComm)",
    "url": "https://www.concordia.ca/academics/undergraduate/business-technology-management.html"
  },
  {
    "id": "concordia-cell-and-molecular-biology-bsc",
    "universityShortCode": "concordia",
    "name": "Cell and Molecular Biology (BSc)",
    "url": "https://www.concordia.ca/academics/undergraduate/cell-molecular-biology.html"
  },
  {
    "id": "concordia-ceramics-bfa",
    "universityShortCode": "concordia",
    "name": "Ceramics (BFA)",
    "url": "https://www.concordia.ca/academics/undergraduate/ceramics.html"
  },
  {
    "id": "concordia-chemical-engineering-beng",
    "universityShortCode": "concordia",
    "name": "Chemical Engineering (BEng)",
    "url": "https://www.concordia.ca/academics/undergraduate/chemical-engineering.html"
  },
  {
    "id": "concordia-chemistry-bsc",
    "universityShortCode": "concordia",
    "name": "Chemistry (BSc)",
    "url": "https://www.concordia.ca/academics/undergraduate/chemistry.html"
  },
  {
    "id": "concordia-child-studies-ba",
    "universityShortCode": "concordia",
    "name": "Child Studies (BA)",
    "url": "https://www.concordia.ca/academics/undergraduate/child-studies.html"
  },
  {
    "id": "concordia-civil-engineering-beng",
    "universityShortCode": "concordia",
    "name": "Civil Engineering (BEng)",
    "url": "https://www.concordia.ca/academics/undergraduate/civil-engineering.html"
  },
  {
    "id": "concordia-classics-ba",
    "universityShortCode": "concordia",
    "name": "Classics (BA)",
    "url": "https://www.concordia.ca/academics/undergraduate/classics.html"
  },
  {
    "id": "concordia-communication-and-cultural-studies-ba",
    "universityShortCode": "concordia",
    "name": "Communication and Cultural Studies (BA)",
    "url": "https://www.concordia.ca/academics/undergraduate/communication-cultural-studies.html"
  },
  {
    "id": "concordia-communication-studies-ba",
    "universityShortCode": "concordia",
    "name": "Communication Studies (BA)",
    "url": "https://www.concordia.ca/academics/undergraduate/communication-studies.html"
  },
  {
    "id": "concordia-community-and-organizational-leadership-cert",
    "universityShortCode": "concordia",
    "name": "Community and Organizational Leadership (Cert)",
    "url": "https://www.concordia.ca/academics/undergraduate/community-organizational-leadership.html"
  },
  {
    "id": "concordia-community-public-affairs-and-policy-studies-ba",
    "universityShortCode": "concordia",
    "name": "Community, Public Affairs and Policy Studies (BA)",
    "url": "https://www.concordia.ca/academics/undergraduate/community-public-affairs-policy-studies.html"
  },
  {
    "id": "concordia-computation-arts-computer-science-bfa",
    "universityShortCode": "concordia",
    "name": "Computation Arts - Computer Science (BFA)",
    "url": "https://www.concordia.ca/academics/undergraduate/comp-arts-computer-science.html"
  },
  {
    "id": "concordia-computation-arts-bfa",
    "universityShortCode": "concordia",
    "name": "Computation Arts (BFA)",
    "url": "https://www.concordia.ca/academics/undergraduate/computation-arts.html"
  },
  {
    "id": "concordia-computational-physics-microprogram",
    "universityShortCode": "concordia",
    "name": "Computational Physics (Microprogram)",
    "url": "https://www.concordia.ca/academics/undergraduate/computational-physics.html"
  },
  {
    "id": "concordia-computer-engineering-beng",
    "universityShortCode": "concordia",
    "name": "Computer Engineering (BEng)",
    "url": "https://www.concordia.ca/academics/undergraduate/computer-engineering.html"
  },
  {
    "id": "concordia-computer-science",
    "universityShortCode": "concordia",
    "name": "Computer Science",
    "url": "https://www.concordia.ca/academics/undergraduate/computer-science-minor.html"
  },
  {
    "id": "concordia-computer-science-computation-arts-bcompsc",
    "universityShortCode": "concordia",
    "name": "Computer Science - Computation Arts (BCompSc)",
    "url": "https://www.concordia.ca/academics/undergraduate/computer-science-comp-arts.html"
  },
  {
    "id": "concordia-computer-science-bcompsc",
    "universityShortCode": "concordia",
    "name": "Computer Science (BCompSc)",
    "url": "https://www.concordia.ca/academics/undergraduate/computer-science.html"
  },
  {
    "id": "concordia-contemporary-dance-bfa",
    "universityShortCode": "concordia",
    "name": "Contemporary Dance (BFA)",
    "url": "https://www.concordia.ca/academics/undergraduate/contemporary-dance.html"
  },
  {
    "id": "concordia-creative-writing-ba",
    "universityShortCode": "concordia",
    "name": "Creative Writing (BA)",
    "url": "https://www.concordia.ca/academics/undergraduate/creative-writing.html"
  },
  {
    "id": "concordia-cybersecurity-bsc",
    "universityShortCode": "concordia",
    "name": "Cybersecurity (BSc)",
    "url": "https://www.concordia.ca/academics/undergraduate/cybersecurity.html"
  },
  {
    "id": "concordia-cybersecurity-engineering-beng",
    "universityShortCode": "concordia",
    "name": "Cybersecurity Engineering (BEng)",
    "url": "https://www.concordia.ca/academics/undergraduate/cybersecurity-engineering.html"
  },
  {
    "id": "concordia-data-intelligence",
    "universityShortCode": "concordia",
    "name": "Data Intelligence",
    "url": "https://www.concordia.ca/academics/undergraduate/data-intelligence.html"
  },
  {
    "id": "concordia-data-science-ba-bsc",
    "universityShortCode": "concordia",
    "name": "Data Science (BA/BSc)",
    "url": "https://www.concordia.ca/academics/undergraduate/arts-science-data-science.html"
  },
  {
    "id": "concordia-data-science-bcompsc",
    "universityShortCode": "concordia",
    "name": "Data Science (BCompSc)",
    "url": "https://www.concordia.ca/academics/undergraduate/computer-science-data-science.html"
  },
  {
    "id": "concordia-design-bfa",
    "universityShortCode": "concordia",
    "name": "Design (BFA)",
    "url": "https://www.concordia.ca/academics/undergraduate/design.html"
  },
  {
    "id": "concordia-diversity-and-the-contemporary-world",
    "universityShortCode": "concordia",
    "name": "Diversity and the Contemporary World",
    "url": "https://www.concordia.ca/academics/undergraduate/diversity-contemporary-world.html"
  },
  {
    "id": "concordia-early-childhood-and-elementary-education-ba",
    "universityShortCode": "concordia",
    "name": "Early Childhood and Elementary Education (BA)",
    "url": "https://www.concordia.ca/academics/undergraduate/early-childhood-elementary-education.html"
  },
  {
    "id": "concordia-ecology-bsc",
    "universityShortCode": "concordia",
    "name": "Ecology (BSc)",
    "url": "https://www.concordia.ca/academics/undergraduate/ecology.html"
  },
  {
    "id": "concordia-economic-policy-microprogram",
    "universityShortCode": "concordia",
    "name": "Economic Policy (Microprogram)",
    "url": "https://www.concordia.ca/academics/undergraduate/economic-policy.html"
  },
  {
    "id": "concordia-economics-ba",
    "universityShortCode": "concordia",
    "name": "Economics (BA)",
    "url": "https://www.concordia.ca/academics/undergraduate/economics.html"
  },
  {
    "id": "concordia-economics-bcomm",
    "universityShortCode": "concordia",
    "name": "Economics (BComm)",
    "url": "https://www.concordia.ca/academics/undergraduate/economics-jmsb.html"
  },
  {
    "id": "concordia-education",
    "universityShortCode": "concordia",
    "name": "Education",
    "url": "https://www.concordia.ca/academics/undergraduate/education.html"
  },
  {
    "id": "concordia-electrical-engineering-beng",
    "universityShortCode": "concordia",
    "name": "Electrical Engineering (BEng)",
    "url": "https://www.concordia.ca/academics/undergraduate/electrical-engineering.html"
  },
  {
    "id": "concordia-electroacoustic-studies-bfa",
    "universityShortCode": "concordia",
    "name": "Electroacoustic Studies (BFA)",
    "url": "https://www.concordia.ca/academics/undergraduate/electroacoustic-studies.html"
  },
  {
    "id": "concordia-english-and-creative-writing-ba",
    "universityShortCode": "concordia",
    "name": "English and Creative Writing (BA)",
    "url": "https://www.concordia.ca/academics/undergraduate/english-and-creativewriting.html"
  },
  {
    "id": "concordia-english-and-history-ba",
    "universityShortCode": "concordia",
    "name": "English and History (BA)",
    "url": "https://www.concordia.ca/academics/undergraduate/english-and-history.html"
  },
  {
    "id": "concordia-english-literature-ba",
    "universityShortCode": "concordia",
    "name": "English Literature (BA)",
    "url": "https://www.concordia.ca/academics/undergraduate/english-literature.html"
  },
  {
    "id": "concordia-entrepreneurship",
    "universityShortCode": "concordia",
    "name": "Entrepreneurship",
    "url": "https://www.concordia.ca/academics/undergraduate/entrepreneurship.html"
  },
  {
    "id": "concordia-environmental-and-sustainability-science-bsc",
    "universityShortCode": "concordia",
    "name": "Environmental and Sustainability Science (BSc)",
    "url": "https://www.concordia.ca/academics/undergraduate/environmental-science.html"
  },
  {
    "id": "concordia-environmental-geography-bsc",
    "universityShortCode": "concordia",
    "name": "Environmental Geography (BSc)",
    "url": "https://www.concordia.ca/academics/undergraduate/environmental-geography.html"
  },
  {
    "id": "concordia-ethics-and-values",
    "universityShortCode": "concordia",
    "name": "Ethics and Values",
    "url": "https://www.concordia.ca/academics/undergraduate/ethics-values.html"
  },
  {
    "id": "concordia-exercise-science-bsc",
    "universityShortCode": "concordia",
    "name": "Exercise Science (BSc)",
    "url": "https://www.concordia.ca/academics/undergraduate/exercise-science.html"
  },
  {
    "id": "concordia-family-life-education-cert",
    "universityShortCode": "concordia",
    "name": "Family Life Education (Cert)",
    "url": "https://www.concordia.ca/academics/undergraduate/family-life-education.html"
  },
  {
    "id": "concordia-fibres-and-material-practices-bfa",
    "universityShortCode": "concordia",
    "name": "Fibres and Material Practices (BFA)",
    "url": "https://www.concordia.ca/academics/undergraduate/fibres-material-practices.html"
  },
  {
    "id": "concordia-film-and-moving-image-studies-bfa",
    "universityShortCode": "concordia",
    "name": "Film and Moving Image Studies (BFA)",
    "url": "https://www.concordia.ca/academics/undergraduate/film-studies.html"
  },
  {
    "id": "concordia-film-animation-bfa",
    "universityShortCode": "concordia",
    "name": "Film Animation (BFA)",
    "url": "https://www.concordia.ca/academics/undergraduate/film-animation.html"
  },
  {
    "id": "concordia-film-production-bfa",
    "universityShortCode": "concordia",
    "name": "Film Production (BFA)",
    "url": "https://www.concordia.ca/academics/undergraduate/film-production.html"
  },
  {
    "id": "concordia-finance-bcomm",
    "universityShortCode": "concordia",
    "name": "Finance (BComm)",
    "url": "https://www.concordia.ca/academics/undergraduate/finance.html"
  },
  {
    "id": "concordia-financial-reporting",
    "universityShortCode": "concordia",
    "name": "Financial Reporting",
    "url": "https://www.concordia.ca/academics/undergraduate/financial-reporting.html"
  },
  {
    "id": "concordia-first-peoples-studies-ba",
    "universityShortCode": "concordia",
    "name": "First Peoples Studies (BA)",
    "url": "https://www.concordia.ca/academics/undergraduate/first-peoples-studies.html"
  },
  {
    "id": "concordia-foundations-for-business-cert",
    "universityShortCode": "concordia",
    "name": "Foundations for Business (Cert)",
    "url": "https://www.concordia.ca/academics/undergraduate/foundations-for-Business.html"
  },
  {
    "id": "concordia-french-studies-a-tudes-frana-aises-ba-cert",
    "universityShortCode": "concordia",
    "name": "French Studies (Ãtudes franÃ§aises) (BA, Cert)",
    "url": "https://www.concordia.ca/academics/undergraduate/french-studies.html"
  },
  {
    "id": "concordia-fundamentals-of-digital-filmmaking-microprogram",
    "universityShortCode": "concordia",
    "name": "Fundamentals of Digital Filmmaking (Microprogram)",
    "url": "https://www.concordia.ca/academics/undergraduate/digital-filmmaking-fundamentals.html"
  },
  {
    "id": "concordia-game-design",
    "universityShortCode": "concordia",
    "name": "Game Design",
    "url": "https://www.concordia.ca/academics/undergraduate/game-design.html"
  },
  {
    "id": "concordia-geospatial-technologies-cert",
    "universityShortCode": "concordia",
    "name": "Geospatial Technologies (Cert)",
    "url": "https://www.concordia.ca/academics/undergraduate/geospatial-technologies.html"
  },
  {
    "id": "concordia-german-studies",
    "universityShortCode": "concordia",
    "name": "German Studies",
    "url": "https://www.concordia.ca/academics/undergraduate/german-minor.html"
  },
  {
    "id": "concordia-health-and-life-sciences-bcompsc",
    "universityShortCode": "concordia",
    "name": "Health and Life Sciences (BCompSc)",
    "url": "https://www.concordia.ca/academics/undergraduate/health-life-sciences.html"
  },
  {
    "id": "concordia-history-ba",
    "universityShortCode": "concordia",
    "name": "History (BA)",
    "url": "https://www.concordia.ca/academics/undergraduate/history.html"
  },
  {
    "id": "concordia-human-environment-ba",
    "universityShortCode": "concordia",
    "name": "Human Environment (BA)",
    "url": "https://www.concordia.ca/academics/undergraduate/human-environment.html"
  },
  {
    "id": "concordia-human-relations-ba",
    "universityShortCode": "concordia",
    "name": "Human Relations (BA)",
    "url": "https://www.concordia.ca/academics/undergraduate/human-relations.html"
  },
  {
    "id": "concordia-human-resource-management-bcomm",
    "universityShortCode": "concordia",
    "name": "Human Resource Management (BComm)",
    "url": "https://www.concordia.ca/academics/undergraduate/human-resource-management.html"
  },
  {
    "id": "concordia-human-rights-studies",
    "universityShortCode": "concordia",
    "name": "Human Rights Studies",
    "url": "https://www.concordia.ca/academics/undergraduate/human-rights.html"
  },
  {
    "id": "concordia-immigration-studies-cert",
    "universityShortCode": "concordia",
    "name": "Immigration Studies (Cert)",
    "url": "https://www.concordia.ca/academics/undergraduate/immigration-studies.html"
  },
  {
    "id": "concordia-indigenous-bridging-program-bcomm",
    "universityShortCode": "concordia",
    "name": "Indigenous Bridging Program (BComm)",
    "url": "https://www.concordia.ca/academics/undergraduate/indigenous-bridging-bcomm.html"
  },
  {
    "id": "concordia-indigenous-bridging-program-beng",
    "universityShortCode": "concordia",
    "name": "Indigenous Bridging Program (BEng)",
    "url": "https://www.concordia.ca/academics/undergraduate/indigenous-bridging-beng.html"
  },
  {
    "id": "concordia-indigenous-bridging-program-bsc",
    "universityShortCode": "concordia",
    "name": "Indigenous Bridging Program (BSc)",
    "url": "https://www.concordia.ca/academics/undergraduate/indigenous-bridging-bsc.html"
  },
  {
    "id": "concordia-indigenous-bridging-program-journalism-ba",
    "universityShortCode": "concordia",
    "name": "Indigenous Bridging Program (Journalism BA)",
    "url": "https://www.concordia.ca/academics/undergraduate/indigenous-bridging-journalism.html"
  },
  {
    "id": "concordia-indigenous-bridging-program-psychology-ba",
    "universityShortCode": "concordia",
    "name": "Indigenous Bridging Program (Psychology BA)",
    "url": "https://www.concordia.ca/academics/undergraduate/indigenous-bridging-psychology.html"
  },
  {
    "id": "concordia-indigenous-land-based-education-microprogram",
    "universityShortCode": "concordia",
    "name": "Indigenous Land-Based Education (Microprogram)",
    "url": "https://www.concordia.ca/academics/undergraduate/indigenous-land-based-education.html"
  },
  {
    "id": "concordia-industrial-engineering-beng",
    "universityShortCode": "concordia",
    "name": "Industrial Engineering (BEng)",
    "url": "https://www.concordia.ca/academics/undergraduate/industrial-engineering.html"
  },
  {
    "id": "concordia-information-systems-audit-and-risk-management",
    "universityShortCode": "concordia",
    "name": "Information Systems Audit and Risk Management",
    "url": "https://www.concordia.ca/academics/undergraduate/infosys-audit-risk-management.html"
  },
  {
    "id": "concordia-innovation-mindset-microprogram",
    "universityShortCode": "concordia",
    "name": "Innovation Mindset (Microprogram)",
    "url": "https://www.concordia.ca/academics/undergraduate/innovation-mindset.html"
  },
  {
    "id": "concordia-interdisciplinary-studies-in-sexuality-ba",
    "universityShortCode": "concordia",
    "name": "Interdisciplinary Studies in Sexuality (BA)",
    "url": "https://www.concordia.ca/academics/undergraduate/sexuality.html"
  },
  {
    "id": "concordia-intermedia-video-performance-and-electronic-arts-bfa",
    "universityShortCode": "concordia",
    "name": "Intermedia (Video, Performance and Electronic Arts) (BFA)",
    "url": "https://www.concordia.ca/academics/undergraduate/intermedia.html"
  },
  {
    "id": "concordia-international-business-bcomm",
    "universityShortCode": "concordia",
    "name": "International Business (BComm)",
    "url": "https://www.concordia.ca/academics/undergraduate/international-business.html"
  },
  {
    "id": "concordia-irish-studies-ba-cert",
    "universityShortCode": "concordia",
    "name": "Irish Studies (BA, Cert)",
    "url": "https://www.concordia.ca/academics/undergraduate/irish-studies.html"
  },
  {
    "id": "concordia-israel-studies",
    "universityShortCode": "concordia",
    "name": "Israel Studies",
    "url": "https://www.concordia.ca/academics/undergraduate/israel-studies.html"
  },
  {
    "id": "concordia-italian-ba",
    "universityShortCode": "concordia",
    "name": "Italian (BA)",
    "url": "https://www.concordia.ca/academics/undergraduate/italian.html"
  },
  {
    "id": "concordia-jazz-studies-bfa",
    "universityShortCode": "concordia",
    "name": "Jazz Studies (BFA)",
    "url": "https://www.concordia.ca/academics/undergraduate/jazz-studies.html"
  },
  {
    "id": "concordia-jewish-studies-microprogram",
    "universityShortCode": "concordia",
    "name": "Jewish Studies (Microprogram)",
    "url": "https://www.concordia.ca/academics/undergraduate/jewish-studies.html"
  },
  {
    "id": "concordia-journalism-ba",
    "universityShortCode": "concordia",
    "name": "Journalism (BA)",
    "url": "https://www.concordia.ca/academics/undergraduate/journalism.html"
  },
  {
    "id": "concordia-judaic-studies-ba",
    "universityShortCode": "concordia",
    "name": "Judaic Studies (BA)",
    "url": "https://www.concordia.ca/academics/undergraduate/judaic-studies.html"
  },
  {
    "id": "concordia-kinesiology-and-clinical-exercise-physiology-bsc",
    "universityShortCode": "concordia",
    "name": "Kinesiology and Clinical Exercise Physiology (BSc)",
    "url": "https://www.concordia.ca/academics/undergraduate/clinical-exercise-physiology.html"
  },
  {
    "id": "concordia-law-and-society",
    "universityShortCode": "concordia",
    "name": "Law and Society",
    "url": "https://www.concordia.ca/academics/undergraduate/law-society.html"
  },
  {
    "id": "concordia-liberal-arts-ba",
    "universityShortCode": "concordia",
    "name": "Liberal Arts (BA)",
    "url": "https://www.concordia.ca/academics/undergraduate/liberal-arts.html"
  },
  {
    "id": "concordia-linguistics-ba",
    "universityShortCode": "concordia",
    "name": "Linguistics (BA)",
    "url": "https://www.concordia.ca/academics/undergraduate/linguistics.html"
  },
  {
    "id": "concordia-management-bcomm",
    "universityShortCode": "concordia",
    "name": "Management (BComm)",
    "url": "https://www.concordia.ca/academics/undergraduate/management.html"
  },
  {
    "id": "concordia-marketing-bcomm",
    "universityShortCode": "concordia",
    "name": "Marketing (BComm)",
    "url": "https://www.concordia.ca/academics/undergraduate/marketing.html"
  },
  {
    "id": "concordia-mathematical-and-computational-finance-ba-bsc",
    "universityShortCode": "concordia",
    "name": "Mathematical and Computational Finance (BA, BSc)",
    "url": "https://www.concordia.ca/academics/undergraduate/mathematical-computational-finance.html"
  },
  {
    "id": "concordia-mathematics-and-statistics-ba-bsc",
    "universityShortCode": "concordia",
    "name": "Mathematics and Statistics (BA, BSc)",
    "url": "https://www.concordia.ca/academics/undergraduate/mathematics-statistics.html"
  },
  {
    "id": "concordia-mechanical-engineering-beng",
    "universityShortCode": "concordia",
    "name": "Mechanical Engineering (BEng)",
    "url": "https://www.concordia.ca/academics/undergraduate/mechanical-engineering.html"
  },
  {
    "id": "concordia-modern-arabic-language-and-culture-cert",
    "universityShortCode": "concordia",
    "name": "Modern Arabic Language and Culture (Cert)",
    "url": "https://www.concordia.ca/academics/undergraduate/modern-arabic.html"
  },
  {
    "id": "concordia-modern-chinese-language-and-culture-cert",
    "universityShortCode": "concordia",
    "name": "Modern Chinese Language and Culture (Cert)",
    "url": "https://www.concordia.ca/academics/undergraduate/modern-chinese.html"
  },
  {
    "id": "concordia-multidisciplinary-studies-in-science",
    "universityShortCode": "concordia",
    "name": "Multidisciplinary Studies in Science",
    "url": "https://www.concordia.ca/academics/undergraduate/multidisciplinary-studies.html"
  },
  {
    "id": "concordia-music-bfa",
    "universityShortCode": "concordia",
    "name": "Music (BFA)",
    "url": "https://www.concordia.ca/academics/undergraduate/music.html"
  },
  {
    "id": "concordia-neuroscience-bsc",
    "universityShortCode": "concordia",
    "name": "Neuroscience (BSc)",
    "url": "https://www.concordia.ca/academics/undergraduate/neuroscience.html"
  },
  {
    "id": "concordia-painting-and-drawing-bfa",
    "universityShortCode": "concordia",
    "name": "Painting and Drawing (BFA)",
    "url": "https://www.concordia.ca/academics/undergraduate/painting-drawing.html"
  },
  {
    "id": "concordia-pastoral-care-cert",
    "universityShortCode": "concordia",
    "name": "Pastoral Care (Cert)",
    "url": "https://www.concordia.ca/academics/undergraduate/pastoral-care.html"
  },
  {
    "id": "concordia-performance-creation-bfa",
    "universityShortCode": "concordia",
    "name": "Performance Creation (BFA)",
    "url": "https://www.concordia.ca/academics/undergraduate/performance-creation.html"
  },
  {
    "id": "concordia-philosophy-ba",
    "universityShortCode": "concordia",
    "name": "Philosophy (BA)",
    "url": "https://www.concordia.ca/academics/undergraduate/philosophy.html"
  },
  {
    "id": "concordia-photography-bfa",
    "universityShortCode": "concordia",
    "name": "Photography (BFA)",
    "url": "https://www.concordia.ca/academics/undergraduate/photography.html"
  },
  {
    "id": "concordia-physics-bsc",
    "universityShortCode": "concordia",
    "name": "Physics (BSc)",
    "url": "https://www.concordia.ca/academics/undergraduate/physics.html"
  },
  {
    "id": "concordia-political-science-ba",
    "universityShortCode": "concordia",
    "name": "Political Science (BA)",
    "url": "https://www.concordia.ca/academics/undergraduate/political-science.html"
  },
  {
    "id": "concordia-print-media-bfa",
    "universityShortCode": "concordia",
    "name": "Print Media (BFA)",
    "url": "https://www.concordia.ca/academics/undergraduate/print-media.html"
  },
  {
    "id": "concordia-professional-writing",
    "universityShortCode": "concordia",
    "name": "Professional Writing",
    "url": "https://www.concordia.ca/academics/undergraduate/professional-writing.html"
  },
  {
    "id": "concordia-psychology-ba-bsc",
    "universityShortCode": "concordia",
    "name": "Psychology (BA, BSc)",
    "url": "https://www.concordia.ca/academics/undergraduate/psychology.html"
  },
  {
    "id": "concordia-pure-and-applied-mathematics-ba-bsc",
    "universityShortCode": "concordia",
    "name": "Pure and Applied Mathematics (BA, BSc)",
    "url": "https://www.concordia.ca/academics/undergraduate/pure-and-applied-mathematics.html"
  },
  {
    "id": "concordia-quantitative-finance-and-insurance",
    "universityShortCode": "concordia",
    "name": "Quantitative Finance and Insurance",
    "url": "https://www.concordia.ca/academics/undergraduate/quantitative-finance-insurance.html"
  },
  {
    "id": "concordia-real-estate",
    "universityShortCode": "concordia",
    "name": "Real Estate",
    "url": "https://www.concordia.ca/academics/undergraduate/real-estate.html"
  },
  {
    "id": "concordia-recreation-and-leisure-studies-ba",
    "universityShortCode": "concordia",
    "name": "Recreation and Leisure Studies (BA)",
    "url": "https://www.concordia.ca/academics/undergraduate/leisure-studies.html"
  },
  {
    "id": "concordia-religions-and-cultures-ba",
    "universityShortCode": "concordia",
    "name": "Religions and Cultures (BA)",
    "url": "https://www.concordia.ca/academics/undergraduate/religion.html"
  },
  {
    "id": "concordia-religious-cultural-and-ethnic-literacy-microprogram",
    "universityShortCode": "concordia",
    "name": "Religious, Cultural and Ethnic Literacy (Microprogram)",
    "url": "https://www.concordia.ca/academics/undergraduate/religious-cultural-ethnic-literacy.html"
  },
  {
    "id": "concordia-scenography-bfa",
    "universityShortCode": "concordia",
    "name": "Scenography (BFA)",
    "url": "https://www.concordia.ca/academics/undergraduate/scenography.html"
  },
  {
    "id": "concordia-science-and-technology-cert",
    "universityShortCode": "concordia",
    "name": "Science and Technology (Cert)",
    "url": "https://www.concordia.ca/academics/undergraduate/science-technology.html"
  },
  {
    "id": "concordia-science-foundations-cert",
    "universityShortCode": "concordia",
    "name": "Science Foundations (Cert)",
    "url": "https://www.concordia.ca/academics/undergraduate/science-foundations.html"
  },
  {
    "id": "concordia-science-journalism",
    "universityShortCode": "concordia",
    "name": "Science Journalism",
    "url": "https://www.concordia.ca/academics/undergraduate/science-journalism.html"
  },
  {
    "id": "concordia-screenwriting-and-film-producing-microprogram",
    "universityShortCode": "concordia",
    "name": "Screenwriting and Film Producing (Microprogram)",
    "url": "https://www.concordia.ca/academics/undergraduate/screenwriting-film-producing.html"
  },
  {
    "id": "concordia-sculpture-bfa",
    "universityShortCode": "concordia",
    "name": "Sculpture (BFA)",
    "url": "https://www.concordia.ca/academics/undergraduate/sculpture.html"
  },
  {
    "id": "concordia-sociology-ba",
    "universityShortCode": "concordia",
    "name": "Sociology (BA)",
    "url": "https://www.concordia.ca/academics/undergraduate/sociology.html"
  },
  {
    "id": "concordia-software-engineering-beng",
    "universityShortCode": "concordia",
    "name": "Software Engineering (BEng)",
    "url": "https://www.concordia.ca/academics/undergraduate/software-engineering.html"
  },
  {
    "id": "concordia-songwriting-and-music-production-microprogram",
    "universityShortCode": "concordia",
    "name": "Songwriting and Music Production (Microprogram)",
    "url": "https://www.concordia.ca/academics/undergraduate/songwriting-music-production.html"
  },
  {
    "id": "concordia-southern-asia-studies-ba",
    "universityShortCode": "concordia",
    "name": "Southern Asia Studies (BA)",
    "url": "https://www.concordia.ca/academics/undergraduate/southern-asia-studies.html"
  },
  {
    "id": "concordia-spanish-hispanic-cultures-and-literatures-ba",
    "universityShortCode": "concordia",
    "name": "Spanish, Hispanic Cultures and Literatures (BA)",
    "url": "https://www.concordia.ca/academics/undergraduate/spanish.html"
  },
  {
    "id": "concordia-statistics-ba-bsc",
    "universityShortCode": "concordia",
    "name": "Statistics (BA, BSc)",
    "url": "https://www.concordia.ca/academics/undergraduate/statistics.html"
  },
  {
    "id": "concordia-studio-art-bfa",
    "universityShortCode": "concordia",
    "name": "Studio Art (BFA)",
    "url": "https://www.concordia.ca/academics/undergraduate/studio-art.html"
  },
  {
    "id": "concordia-supply-chain-operations-management-bcomm",
    "universityShortCode": "concordia",
    "name": "Supply Chain Operations Management (BComm)",
    "url": "https://www.concordia.ca/academics/undergraduate/supply-chain-operations-management.html"
  },
  {
    "id": "concordia-sustainability-principles-microprogram",
    "universityShortCode": "concordia",
    "name": "Sustainability Principles (Microprogram)",
    "url": "https://www.concordia.ca/academics/undergraduate/sustainability-principles.html"
  },
  {
    "id": "concordia-sustainability-studies",
    "universityShortCode": "concordia",
    "name": "Sustainability Studies",
    "url": "https://www.concordia.ca/academics/undergraduate/sustainability-studies.html"
  },
  {
    "id": "concordia-systems-and-information-biology-bsc",
    "universityShortCode": "concordia",
    "name": "Systems and Information Biology (BSc)",
    "url": "https://www.concordia.ca/academics/undergraduate/systems-information-biology.html"
  },
  {
    "id": "concordia-teaching-english-as-a-second-language-cert",
    "universityShortCode": "concordia",
    "name": "Teaching English as a Second Language (Cert)",
    "url": "https://www.concordia.ca/academics/undergraduate/tesl-cert.html"
  },
  {
    "id": "concordia-teaching-english-as-a-second-language-tesl-bed",
    "universityShortCode": "concordia",
    "name": "Teaching English as a Second Language (TESL) (BEd)",
    "url": "https://www.concordia.ca/academics/undergraduate/teaching-english-second-language.html"
  },
  {
    "id": "concordia-theatre",
    "universityShortCode": "concordia",
    "name": "Theatre",
    "url": "https://www.concordia.ca/academics/undergraduate/theatre-minor.html"
  },
  {
    "id": "concordia-theological-studies-ba",
    "universityShortCode": "concordia",
    "name": "Theological Studies (BA)",
    "url": "https://www.concordia.ca/academics/undergraduate/theological-studies.html"
  },
  {
    "id": "concordia-therapeutic-recreation-ba",
    "universityShortCode": "concordia",
    "name": "Therapeutic Recreation (BA)",
    "url": "https://www.concordia.ca/academics/undergraduate/therapeutic-recreation.html"
  },
  {
    "id": "concordia-traduction-translation-ba",
    "universityShortCode": "concordia",
    "name": "Traduction (Translation) (BA)",
    "url": "https://www.concordia.ca/academics/undergraduate/translation.html"
  },
  {
    "id": "concordia-urban-studies-ba",
    "universityShortCode": "concordia",
    "name": "Urban Studies (BA)",
    "url": "https://www.concordia.ca/academics/undergraduate/urban-planning-urban-studies.html"
  },
  {
    "id": "concordia-web-design-and-user-interface-microprogram",
    "universityShortCode": "concordia",
    "name": "Web Design and User Interface (Microprogram)",
    "url": "https://www.concordia.ca/academics/undergraduate/web-design-user-interface.html"
  },
  {
    "id": "concordia-womens-studies-ba-cert",
    "universityShortCode": "concordia",
    "name": "Women's Studies (BA, Cert)",
    "url": "https://www.concordia.ca/academics/undergraduate/womens-studies.html"
  },
  {
    "id": "mcgill-computer-science-bsc",
    "universityShortCode": "mcgill",
    "name": "Computer Science (BSc)",
    "url": "https://www.mcgill.ca/study/faculties/science/undergraduate/programs/bachelor-science-bsc-major-computer-science"
  },
  {
    "id": "mcgill-desautels-faculty-of-management-bcom",
    "universityShortCode": "mcgill",
    "name": "Desautels Faculty of Management (BCom)",
    "url": "https://www.mcgill.ca/desautels/programs/bcom"
  },
  {
    "id": "mcgill-law-bcl-jd",
    "universityShortCode": "mcgill",
    "name": "Law (BCL/JD)",
    "url": "https://www.mcgill.ca/law/bcl-jd"
  },
  {
    "id": "mcgill-mechanical-engineering-beng",
    "universityShortCode": "mcgill",
    "name": "Mechanical Engineering (BEng)",
    "url": "https://www.mcgill.ca/study/faculties/engineering/undergraduate/programs/bachelor-engineering-beng-mechanical-engineering"
  },
  {
    "id": "mcgill-medicine-mdcm",
    "universityShortCode": "mcgill",
    "name": "Medicine (MDCM)",
    "url": "https://www.mcgill.ca/medadmissions/programs/mdcm"
  },
  {
    "id": "mcgill-software-engineering-bse",
    "universityShortCode": "mcgill",
    "name": "Software Engineering (BSE)",
    "url": "https://www.mcgill.ca/study/faculties/engineering/undergraduate/programs/bachelor-software-engineering-bse-software-engineering"
  },
  {
    "id": "udem-amenagement",
    "universityShortCode": "udem",
    "name": "Aménagement",
    "url": "https://admission.umontreal.ca/programmes/amenagement/"
  },
  {
    "id": "udem-arts-et-musique",
    "universityShortCode": "udem",
    "name": "Arts et musique",
    "url": "https://admission.umontreal.ca/programmes/arts-et-musique/"
  },
  {
    "id": "udem-communication",
    "universityShortCode": "udem",
    "name": "Communication",
    "url": "https://admission.umontreal.ca/programmes/communication/"
  },
  {
    "id": "udem-droit",
    "universityShortCode": "udem",
    "name": "Droit",
    "url": "https://admission.umontreal.ca/programmes/droit/"
  },
  {
    "id": "udem-economie-et-politique",
    "universityShortCode": "udem",
    "name": "Économie et politique",
    "url": "https://admission.umontreal.ca/programmes/economie-et-politique/"
  },
  {
    "id": "udem-enseignement-et-sciences-de-leducation",
    "universityShortCode": "udem",
    "name": "Enseignement et sciences de l'éducation",
    "url": "https://admission.umontreal.ca/programmes/enseignement-et-education/"
  },
  {
    "id": "udem-environnement-et-developpement-durable",
    "universityShortCode": "udem",
    "name": "Environnement et développement durable",
    "url": "https://admission.umontreal.ca/programmes/environnement-et-developpement-durable/"
  },
  {
    "id": "udem-lettres-et-langues",
    "universityShortCode": "udem",
    "name": "Lettres et langues",
    "url": "https://admission.umontreal.ca/programmes/lettres-et-langues/"
  },
  {
    "id": "udem-programmes-individualises",
    "universityShortCode": "udem",
    "name": "Programmes individualisés",
    "url": "https://admission.umontreal.ca/programmes/individualises/"
  },
  {
    "id": "udem-sciences-de-ladministration-et-gestion",
    "universityShortCode": "udem",
    "name": "Sciences de l'administration et gestion",
    "url": "https://admission.umontreal.ca/programmes/sciences-de-ladministration-et-gestion/"
  },
  {
    "id": "udem-sciences-de-ladministration-et-gestion-2",
    "universityShortCode": "udem",
    "name": "Sciences de l’administration et gestion",
    "url": "https://admission.umontreal.ca/programmes/sciences-de-ladministration-et-gestion/"
  },
  {
    "id": "udem-sciences-de-la-sante",
    "universityShortCode": "udem",
    "name": "Sciences de la santé",
    "url": "https://admission.umontreal.ca/programmes/sciences-de-la-sante/"
  },
  {
    "id": "udem-sciences-de-la-vie",
    "universityShortCode": "udem",
    "name": "Sciences de la vie",
    "url": "https://admission.umontreal.ca/programmes/sciences-de-la-vie/"
  },
  {
    "id": "udem-sciences-humaines",
    "universityShortCode": "udem",
    "name": "Sciences humaines",
    "url": "https://admission.umontreal.ca/programmes/sciences-humaines/"
  },
  {
    "id": "udem-sciences-pures-et-sciences-appliquees",
    "universityShortCode": "udem",
    "name": "Sciences pures et sciences appliquées",
    "url": "https://admission.umontreal.ca/programmes/sciences-pures-et-sciences-appliquees/"
  },
  {
    "id": "udem-sciences-sociales",
    "universityShortCode": "udem",
    "name": "Sciences sociales",
    "url": "https://admission.umontreal.ca/programmes/sciences-sociales/"
  },
  {
    "id": "udem-sciences-sociales-intervention",
    "universityShortCode": "udem",
    "name": "Sciences sociales : intervention",
    "url": "https://admission.umontreal.ca/programmes/sciences-sociales-intervention/"
  },
  {
    "id": "udem-technologies-de-linformation-et-des-communications",
    "universityShortCode": "udem",
    "name": "Technologies de l'information et des communications",
    "url": "https://admission.umontreal.ca/programmes/technologie-de-linformation-et-des-communications/"
  },
  {
    "id": "udem-technologies-de-linformation-et-des-communications-2",
    "universityShortCode": "udem",
    "name": "Technologies de l’information et des communications",
    "url": "https://admission.umontreal.ca/programmes/technologie-de-linformation-et-des-communications/"
  },
  {
    "id": "udem-theologie-et-sciences-des-religions",
    "universityShortCode": "udem",
    "name": "Théologie et sciences des religions",
    "url": "https://admission.umontreal.ca/programmes/theologie-et-sciences-des-religions/"
  },
  {
    "id": "uqam-baccalaureat-en-administration",
    "universityShortCode": "uqam",
    "name": "Baccalauréat en administration",
    "url": "https://etudier.uqam.ca/programme?code=7314"
  },
  {
    "id": "uqam-baccalaureat-en-droit",
    "universityShortCode": "uqam",
    "name": "Baccalauréat en droit",
    "url": "https://etudier.uqam.ca/programme?code=7308"
  },
  {
    "id": "uqam-baccalaureat-en-informatique-et-genie-logiciel",
    "universityShortCode": "uqam",
    "name": "Baccalauréat en informatique et génie logiciel",
    "url": "https://etudier.uqam.ca/programme?code=7825"
  },
  {
    "id": "uqam-baccalaureat-en-psychologie",
    "universityShortCode": "uqam",
    "name": "Baccalauréat en psychologie",
    "url": "https://etudier.uqam.ca/programme?code=7356"
  },
  {
    "id": "ulaval-baccalaureat-en-droit",
    "universityShortCode": "ulaval",
    "name": "Baccalauréat en droit",
    "url": "https://www.ulaval.ca/les-etudes/programmes/repertoire/details/baccalaureat-en-droit-ll-b.html"
  },
  {
    "id": "ulaval-baccalaureat-en-genie-logiciel",
    "universityShortCode": "ulaval",
    "name": "Baccalauréat en génie logiciel",
    "url": "https://www.ulaval.ca/les-etudes/programmes/repertoire/details/baccalaureat-en-genie-logiciel-bing.html"
  },
  {
    "id": "ulaval-baccalaureat-en-informatique",
    "universityShortCode": "ulaval",
    "name": "Baccalauréat en informatique",
    "url": "https://www.ulaval.ca/les-etudes/programmes/repertoire/details/baccalaureat-en-informatique-ba.html"
  },
  {
    "id": "ulaval-doctorat-de-premier-cycle-en-medecine",
    "universityShortCode": "ulaval",
    "name": "Doctorat de premier cycle en médecine",
    "url": "https://www.ulaval.ca/les-etudes/programmes/repertoire/details/doctorat-de-premier-cycle-en-medecine-md.html"
  }
];
